var searchData=
[
  ['id_0',['id',['../classidol_1_1Object.html#ac8e398b9b937f08b1c5dbd2b32414036',1,'idol::Object::id()'],['../classidol_1_1Param.html#a41243b2248da219ea1467bb0898e025a',1,'idol::Param::id()']]],
  ['identity_1',['identity',['../structidol_1_1identity.html',1,'idol']]],
  ['idol_2',['idol',['../example_mixed_integer_bin_bap.html#autotoc_md2',1,'Implementation in idol'],['../example_mixed_integer_gap_bap.html#autotoc_md6',1,'Implementation in idol'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md14',1,'Implementation in idol']]],
  ['idol_20c_20library_3',['The &lt;span class=&quot;tt&quot;&gt;idol&lt;/span&gt; C++ Library',['../index.html#getting_started_with_idol',1,'']]],
  ['idol_20using_20cmake_4',['Linking with &lt;span class=&quot;tt&quot;&gt;idol&lt;/span&gt; using CMake',['../lib_installation.html#lib_linking',1,'']]],
  ['idol_3a_3atolerance_5',['Tolerance',['../namespaceidol_1_1Tolerance.html',1,'idol']]],
  ['idol_5fcl_6',['What is idol_cl?',['../cli_basics.html#cli_what_is',1,'']]],
  ['implementation_20in_20idol_7',['Implementation in idol',['../example_mixed_integer_bin_bap.html#autotoc_md2',1,'Implementation in idol'],['../example_mixed_integer_gap_bap.html#autotoc_md6',1,'Implementation in idol'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md14',1,'Implementation in idol']]],
  ['in_20idol_8',['in idol',['../example_mixed_integer_bin_bap.html#autotoc_md2',1,'Implementation in idol'],['../example_mixed_integer_gap_bap.html#autotoc_md6',1,'Implementation in idol'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md14',1,'Implementation in idol']]],
  ['inequalities_9',['Deactivating Kleinart et al. (2020) Valid Inequalities',['../cli_bilevel_kkt.html#kkt_kleinert_vi',1,'']]],
  ['infeasibilitystrategyfactory_10',['InfeasibilityStrategyFactory',['../classidol_1_1DantzigWolfe_1_1InfeasibilityStrategyFactory.html',1,'idol::DantzigWolfe']]],
  ['info_11',['Info',['../classidol_1_1Logs_1_1BranchAndBound_1_1Info.html',1,'idol::Logs::BranchAndBound::Info&lt; NodeInfoT &gt;'],['../classidol_1_1Logs_1_1DantzigWolfe_1_1Info.html',1,'idol::Logs::DantzigWolfe::Info']]],
  ['initialize_12',['initialize',['../classidol_1_1BranchAndBoundCallback.html#acfa261050e03bf300457218a38be51d6',1,'idol::BranchAndBoundCallback::initialize()'],['../classidol_1_1Cuts_1_1KnapsackCover_1_1Strategy.html#ac3b637513554dd08621768a8dfd79dff',1,'idol::Cuts::KnapsackCover::Strategy::initialize()']]],
  ['input_20format_13',['Input Format',['../cli_input_format.html',1,'']]],
  ['input_20format_20for_20bilevel_20problems_14',['Input Format for Bilevel Problems',['../cli_input_format_bilevel.html',1,'']]],
  ['input_20format_20for_20milps_15',['Input Format for MILPs',['../cli_input_format_milp.html',1,'']]],
  ['input_20format_20for_20robust_20problems_16',['Input Format for Robust Problems',['../cli_input_format_robust.html',1,'']]],
  ['install_17',['Step 4 — Install',['../build_from_source.html#step_install',1,'']]],
  ['installation_18',['Installation',['../cli_installation.html',1,'Installation'],['../lib_installation.html',1,'Installation'],['../lib_installation.html#lib_install',1,'Installation']]],
  ['installation_19',['Step 5 — Verify installation',['../build_from_source.html#step_verify',1,'']]],
  ['installation_20directory_20',['Custom installation directory',['../build_from_source.html#cmake_install_prefix',1,'']]],
  ['installation_20guidelines_21',['Installation guidelines',['../installation.html',1,'']]],
  ['instance_22',['Instance',['../classidol_1_1Problems_1_1FLP_1_1Instance.html',1,'idol::Problems::FLP::Instance'],['../classidol_1_1Problems_1_1GAP_1_1Instance.html',1,'idol::Problems::GAP::Instance'],['../classidol_1_1Problems_1_1KP_1_1Instance.html',1,'idol::Problems::KP::Instance'],['../classidol_1_1Problems_1_1MKP_1_1Instance.html',1,'idol::Problems::MKP::Instance'],['../classidol_1_1Problems_1_1SRP_1_1Instance.html',1,'idol::Problems::SRP::Instance']]],
  ['instances_23',['Instances',['../cli_instances.html',1,'']]],
  ['instructions_24',['Build instructions',['../build_from_source.html#build_steps',1,'']]],
  ['integer_25',['Integer',['../namespaceidol_1_1Tolerance.html#abc666019c56885dd181bef0e1ce49088',1,'idol::Tolerance']]],
  ['integer_20bilevel_20optimization_26',['Mixed-integer bilevel optimization',['../examples_bilevel.html#examples_bilevel_mixed_integer',1,'']]],
  ['integer_20optimization_27',['integer optimization',['../examples_mixed_integer.html',1,'Mixed-integer optimization'],['../stable_features_mixed_integer.html',1,'Mixed-integer optimization']]],
  ['integermaster_28',['IntegerMaster',['../classidol_1_1Heuristics_1_1IntegerMaster.html',1,'idol::Heuristics']]],
  ['integrality_20constraints_29',['Integrality Constraints',['../example_mixed_integer_tsp_gurobi.html#autotoc_md12',1,'']]],
  ['interface_30',['Modeling interface',['../test_modeling_interface.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20cplex_31',['Interfacing Cplex',['../test_wrapper_Cplex.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20cplex_20via_20osi_32',['Interfacing Cplex via Osi',['../test_wrapper_OsiCplex.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20glpk_33',['Interfacing GLPK',['../test_wrapper_GLPK.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20gurobi_34',['Interfacing Gurobi',['../test_wrapper_Gurobi.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20highs_35',['Interfacing HiGHS',['../test_wrapper_HiGHS.html',1,'stable_features_mixed_integer']]],
  ['introduction_36',['Introduction',['../cli_bilevel_kkt.html#kkt_introduction',1,'']]],
  ['is_37',['is',['../classidol_1_1Param.html#a3a60236e5a635f6611c172b74777d93a',1,'idol::Param']]],
  ['is_20idol_5fcl_38',['What is idol_cl?',['../cli_basics.html#cli_what_is',1,'']]],
  ['is_20this_20a_20mip_20solver_39',['Is this a MIP Solver?',['../index.html#is_this_a_mip_solver',1,'']]],
  ['is_5fin_40',['is_in',['../classidol_1_1Object.html#aa25899704860cb066f885015ec1f11f3',1,'idol::Object']]],
  ['item_41',['Item',['../structidol_1_1Cuts_1_1KnapsackCover_1_1Strategy_1_1KnapsackStructure_1_1Item.html',1,'idol::Cuts::KnapsackCover::Strategy::KnapsackStructure']]],
  ['iterationplot_42',['IterationPlot',['../classidol_1_1Optimizers_1_1PADM_1_1IterationPlot.html',1,'idol::Optimizers::PADM']]],
  ['iterator_43',['iterator',['../classidol_1_1Range_1_1iterator.html',1,'idol::Range']]],
  ['iteratorforward_44',['IteratorForward',['../classidol_1_1IteratorForward.html',1,'idol']]],
  ['iteratorforward_3c_20std_3a_3alist_3c_20std_3a_3apair_3c_20keyt_2c_20valuet_20_3e_20_3e_20_3e_45',['IteratorForward&lt; std::list&lt; std::pair&lt; KeyT, ValueT &gt; &gt; &gt;',['../classidol_1_1IteratorForward.html',1,'idol']]],
  ['its_20kkt_20based_20single_20level_20reformulation_46',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]]
];
