var searchData=
[
  ['padm_0',['PADM',['../classidol_1_1Bilevel_1_1PADM.html',1,'idol::Bilevel::PADM'],['../classidol_1_1Optimizers_1_1Bilevel_1_1PADM.html',1,'idol::Optimizers::Bilevel::PADM'],['../classidol_1_1Optimizers_1_1PADM.html',1,'idol::Optimizers::PADM'],['../classidol_1_1PADM.html',1,'idol::PADM']]],
  ['pair_1',['Pair',['../structidol_1_1Pair.html',1,'idol']]],
  ['pair_3c_20t_2c_20t_20_3e_2',['Pair&lt; T, T &gt;',['../structidol_1_1Pair.html',1,'idol']]],
  ['parallel_20pricing_3',['Parallel Pricing',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_parallel',1,'']]],
  ['param_4',['Param',['../classidol_1_1Param.html',1,'idol::Param'],['../classidol_1_1Param.html#abddc89cb7892eb4841efd6c219f8cfc1',1,'idol::Param::Param(const Var &amp;t_var)'],['../classidol_1_1Param.html#abd6102b12d3fccbf8ea7bdda12beda97',1,'idol::Param::Param(const Ctr &amp;t_ctr)'],['../classidol_1_1Param.html#aeaf61eb9ea6b75a37e0ff1554e24358b',1,'idol::Param::Param(const Param &amp;t_param)=default'],['../classidol_1_1Param.html#a7928ae7e1cd355ab0b3c5ef5442c8d68',1,'idol::Param::Param(Param &amp;&amp;t_param) noexcept=default']]],
  ['parameters_5',['Handling of Default Tolerances and Parameters',['../lib_milp_basics_advanced_environment.html#lib_milp_basics_advanced_environment_tolerances',1,'']]],
  ['party_20tools_6',['Third Party Tools',['../about.html#autotoc_md22',1,'']]],
  ['path_20problem_20rspp_7',['Resource-constrained shortest path problem (RSPP)',['../example_mixed_integer_rspp_bap.html#autotoc_md7',1,'']]],
  ['penaltymethod_8',['PenaltyMethod',['../classidol_1_1PenaltyMethod.html',1,'idol']]],
  ['penaltyupdate_9',['PenaltyUpdate',['../classidol_1_1PenaltyUpdate.html',1,'idol']]],
  ['pess_10',['zeng-pess',['../example_bilevel_zeng_pess.html',1,'examples_bilevel']]],
  ['pessimistic_20bilevel_20optimization_11',['Pessimistic bilevel optimization',['../examples_bilevel.html#examples_bilevel_mixed_integer_pessimistic',1,'']]],
  ['pessimistic_20bilevel_20problem_12',['Solving A Pessimistic Bilevel Problem',['../cli_bilevel_basics.html#cli_bilevel_basics_pessimistic',1,'']]],
  ['pessimisticasoptimistic_13',['PessimisticAsOptimistic',['../classidol_1_1Bilevel_1_1PessimisticAsOptimistic.html',1,'idol::Bilevel::PessimisticAsOptimistic'],['../classidol_1_1Optimizers_1_1Bilevel_1_1PessimisticAsOptimistic.html',1,'idol::Optimizers::Bilevel::PessimisticAsOptimistic']]],
  ['phase_20i_14',['Making the Master Problem Feasible (Phase I)',['../lib_milp_branch_and_price_cg_phaseI.html',1,'lib_milp_branch_and_price']]],
  ['phases_15',['Strong Branching with Phases',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_phases',1,'']]],
  ['planes_16',['Cutting Planes',['../lib_milp_bnb_cutting_planes.html',1,'lib_milp_branch_and_bound']]],
  ['point_17',['Point',['../classidol_1_1Point.html',1,'idol']]],
  ['point_3c_20ctr_20_3e_18',['Point&lt; Ctr &gt;',['../classidol_1_1Point.html',1,'idol']]],
  ['point_3c_20var_20_3e_19',['Point&lt; Var &gt;',['../classidol_1_1Point.html',1,'idol']]],
  ['pool_20',['The Cut Pool',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_cut_pool',1,'']]],
  ['pool_20clean_20up_21',['Column Pool Clean Up',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_clean_up',1,'']]],
  ['pool_20size_22',['Solution Pool Size',['../lib_milp_bnb_options.html#lib_milp_bnb_options_solution_pool',1,'']]],
  ['presolve_23',['Presolve',['../classidol_1_1Presolve.html',1,'idol::Presolve'],['../lib_milp_bnb_presolve.html',1,'Presolve']]],
  ['price_24',['Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'About Branch-and-Cut-and-Price'],['../lib_milp_branch_and_price.html',1,'Branch-and-Cut-and-Price']]],
  ['price_20algorithm_25',['Branch-and-Price algorithm',['../example_mixed_integer_rspp_bap.html#autotoc_md8',1,'']]],
  ['price_20algorithm_26',['Branch-and-price algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'']]],
  ['pricing_27',['Pricing',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_parallel',1,'Parallel Pricing'],['../lib_milp_branch_and_price_cg_HeuristicPricing.html',1,'Using Heuristics for Pricing']]],
  ['pricing_20callback_28',['Using Your Own Pricing Callback',['../lib_milp_branch_and_price_cg_callback.html',1,'lib_milp_branch_and_price']]],
  ['pricing_20problem_29',['Deriving the Pricing Problem',['../example_mixed_integer_gap_bap.html#autotoc_md5',1,'']]],
  ['pricing_20subproblem_30',['Pricing Subproblem',['../example_mixed_integer_rspp_bap.html#autotoc_md10',1,'']]],
  ['primal_5fsolution_31',['primal_solution',['../classidol_1_1Callback.html#ac1a19a08051cc57531e9c14422a026c0',1,'idol::Callback']]],
  ['priorities_32',['Branching with Priorities',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_BranchingWithPriority',1,'']]],
  ['problem_33',['Problem',['../example_mixed_integer_gap_bap.html#autotoc_md5',1,'Deriving the Pricing Problem'],['../cli_bilevel_basics.html#cli_bilevel_basics_pessimistic',1,'Solving A Pessimistic Bilevel Problem'],['../cli_robust_basics.html#cli_robust_basics_aro_solving',1,'Solving a Two-Stage Robust Problem'],['../cli_bilevel_basics.html#cli_bilevel_basics_optimistic',1,'Solving An Optimistic Bilevel Problem'],['../example_mixed_integer_rspp_bap.html#autotoc_md9',1,'The Master Problem']]],
  ['problem_20feasible_20phase_20i_34',['Making the Master Problem Feasible (Phase I)',['../lib_milp_branch_and_price_cg_phaseI.html',1,'lib_milp_branch_and_price']]],
  ['problem_20rspp_35',['Resource-constrained shortest path problem (RSPP)',['../example_mixed_integer_rspp_bap.html#autotoc_md7',1,'']]],
  ['problems_36',['Basics of the Command Line Interface for Robust Problems',['../cli_robust_basics.html',1,'']]],
  ['problems_20via_20its_20kkt_20based_20single_20level_20reformulation_37',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['product_38',['Product',['../classidol_1_1NodeScoreFunctions_1_1Product.html',1,'idol::NodeScoreFunctions']]],
  ['providing_20bounds_20on_20the_20dual_20variables_39',['The File Format for Providing Bounds on the Dual Variables',['../cli_bilevel_kkt.html#kkt_big_m_file',1,'']]],
  ['pseudo_20cost_20branching_40',['Pseudo Cost Branching',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_PseudoCost',1,'']]],
  ['pseudocost_41',['PseudoCost',['../classidol_1_1BranchingRules_1_1PseudoCost.html',1,'idol::BranchingRules::PseudoCost&lt; NodeInfoT &gt;'],['../classidol_1_1PseudoCost.html',1,'idol::PseudoCost']]]
];
