var searchData=
[
  ['c_20library_0',['C Library',['../index.html#getting_started_with_idol',1,'The &lt;span class=&quot;tt&quot;&gt;idol&lt;/span&gt; C++ Library'],['../lib_tutorials.html',1,'Tutorials for the C++ Library']]],
  ['callback_1',['Callback',['../classidol_1_1Callback.html',1,'idol::Callback'],['../lib_milp_branch_and_price_cg_callback.html',1,'Using Your Own Pricing Callback'],['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_specific',1,'Writing a Branch-and-Bound-Specific Callback'],['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_universal',1,'Writing a Universal Callback']]],
  ['callbackasbranchandboundcallback_2',['CallbackAsBranchAndBoundCallback',['../classidol_1_1CallbackAsBranchAndBoundCallback.html',1,'idol']]],
  ['callbackfactory_3',['CallbackFactory',['../classidol_1_1CallbackFactory.html',1,'idol']]],
  ['callbacki_4',['CallbackI',['../classidol_1_1CallbackI.html',1,'idol']]],
  ['callbacks_5',['Callbacks',['../lib_milp_bnb_callbacks.html',1,'lib_milp_branch_and_bound']]],
  ['can_20you_20do_20with_20it_6',['What is a Model and What Can You Do with It?',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_what',1,'']]],
  ['cannot_20find_20cplex_20glpk_20gurobi_20highs_20or_20any_20other_20solver_7',['Cannot find Cplex, GLPK, Gurobi, HiGHS, or any other solver',['../cannot_find_solver.html',1,'']]],
  ['ccg_8',['flp-ccg',['../example_robust_flp_ccg.html',1,'examples_robust']]],
  ['cgl_9',['Using the Coin-OR Cut Generation Library (Cgl)',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_cgl',1,'']]],
  ['cgl_20support_10',['Enable Cgl support',['../build_from_source.html#cmake_cgl',1,'']]],
  ['cglcutcallback_11',['CglCutCallback',['../classidol_1_1CglCutCallback.html',1,'idol']]],
  ['cglcutgenerator_12',['CglCutGenerator',['../classCglCutGenerator.html',1,'']]],
  ['changing_20the_20scoring_20function_13',['Changing the Scoring Function',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_scoring',1,'']]],
  ['changing_20the_20underlying_20milp_20solver_14',['Changing the Underlying MILP Solver',['../cli_bilevel_kkt.html#kkt_other_milp_solver',1,'']]],
  ['cite_15',['How to cite',['../about.html#autotoc_md15',1,'']]],
  ['clean_20up_16',['Column Pool Clean Up',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_clean_up',1,'']]],
  ['clone_20the_20repository_17',['Step 1 — Clone the repository',['../build_from_source.html#step_clone',1,'']]],
  ['cmake_18',['Linking with &lt;span class=&quot;tt&quot;&gt;idol&lt;/span&gt; using CMake',['../lib_installation.html#lib_linking',1,'']]],
  ['cmake_20fetchcontent_19',['Automatic Download using CMake &lt;span class=&quot;tt&quot;&gt;FetchContent&lt;/span&gt;',['../lib_installation.html#lib_install_cmake',1,'']]],
  ['cmake_20options_20',['CMake Options',['../build_from_source.html#cmake_options',1,'']]],
  ['coin_20or_20cut_20generation_20library_20cgl_21',['Using the Coin-OR Cut Generation Library (Cgl)',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_cgl',1,'']]],
  ['column_22',['column',['../classidol_1_1TempVar.html#adb5a7b0a207fe80523ebdab86c3797b6',1,'idol::TempVar::column() const'],['../classidol_1_1TempVar.html#ad68d7613eea549f903504c873956efc4',1,'idol::TempVar::column()']]],
  ['column_20generation_20via_20in_20out_20separation_23',['Stabilizing Column Generation via in-out Separation',['../lib_milp_branch_and_price_cg_in_out.html',1,'lib_milp_branch_and_price']]],
  ['column_20pool_20clean_20up_24',['Column Pool Clean Up',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_clean_up',1,'']]],
  ['columnandconstraintgeneration_25',['ColumnAndConstraintGeneration',['../classidol_1_1Optimizers_1_1Robust_1_1ColumnAndConstraintGeneration.html',1,'idol::Optimizers::Robust::ColumnAndConstraintGeneration'],['../classidol_1_1Robust_1_1ColumnAndConstraintGeneration.html',1,'idol::Robust::ColumnAndConstraintGeneration']]],
  ['columngeneration_26',['ColumnGeneration',['../classidol_1_1Optimizers_1_1DantzigWolfeDecomposition_1_1ColumnGeneration.html',1,'idol::Optimizers::DantzigWolfeDecomposition']]],
  ['coluna_27',['Coluna',['../classidol_1_1Optimizers_1_1Coluna.html',1,'idol::Optimizers']]],
  ['command_20line_20interface_28',['Tutorials for the Command Line Interface',['../cli_tutorials.html',1,'']]],
  ['command_20line_20interface_20for_20bilevel_20optimization_29',['Basics of the Command Line Interface for Bilevel Optimization',['../cli_bilevel_basics.html',1,'']]],
  ['command_20line_20interface_20for_20milps_30',['Basics of the Command Line Interface for MILPs',['../cli_milp_basics.html',1,'']]],
  ['command_20line_20interface_20for_20robust_20problems_31',['Basics of the Command Line Interface for Robust Problems',['../cli_robust_basics.html',1,'']]],
  ['commutativepair_32',['CommutativePair',['../structidol_1_1CommutativePair.html',1,'idol']]],
  ['configure_20and_20build_33',['Step 3 — Configure and build',['../build_from_source.html#step_configure',1,'']]],
  ['const_5fiterator_34',['const_iterator',['../classidol_1_1NodeSet_1_1const__iterator.html',1,'idol::NodeSet']]],
  ['constiteratorforward_35',['ConstIteratorForward',['../classidol_1_1ConstIteratorForward.html',1,'idol']]],
  ['constiteratorforward_3c_20by_5flevel_5ft_2c_20const_5fiterator_20_3e_36',['ConstIteratorForward&lt; by_level_t, const_iterator &gt;',['../classidol_1_1ConstIteratorForward.html',1,'idol']]],
  ['constiteratorforward_3c_20by_5fobjective_5fvalue_5ft_2c_20const_5fiterator_20_3e_37',['ConstIteratorForward&lt; by_objective_value_t, const_iterator &gt;',['../classidol_1_1ConstIteratorForward.html',1,'idol']]],
  ['constiteratorforward_3c_20std_3a_3alist_3c_20std_3a_3apair_3c_20keyt_2c_20valuet_20_3e_20_3e_20_3e_38',['ConstIteratorForward&lt; std::list&lt; std::pair&lt; KeyT, ValueT &gt; &gt; &gt;',['../classidol_1_1ConstIteratorForward.html',1,'idol']]],
  ['constraint_20matrix_20uncertainty_39',['Constraint Matrix Uncertainty',['../cli_robust_basics.html#cli_robust_mat_file',1,'']]],
  ['constraints_40',['Constraints',['../lib_milp_basics_advanced_constraints.html',1,'Constraints'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md10',1,'Degree Constraints'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md12',1,'Integrality Constraints'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md11',1,'Sub-Tour Elimination Constraints']]],
  ['constructor_41',['Using the Variable Constructor',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_create_env',1,'']]],
  ['continuous_20bilevel_20optimization_42',['Continuous bilevel optimization',['../examples_bilevel.html#examples_bilevel_continuous',1,'']]],
  ['convexification_43',['Convexification',['../classidol_1_1Optimizers_1_1Robust_1_1Convexification.html',1,'idol::Optimizers::Robust::Convexification'],['../classidol_1_1Robust_1_1Convexification.html',1,'idol::Robust::Convexification']]],
  ['copying_20and_20moving_20models_44',['Copying and Moving Models',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_copy',1,'']]],
  ['cost_20branching_45',['Pseudo Cost Branching',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_PseudoCost',1,'']]],
  ['count_46',['count',['../classidol_1_1Timer.html#aaf86be1f45ac1de1c97598830faea303',1,'idol::Timer']]],
  ['cplex_47',['Cplex',['../classidol_1_1Cplex.html',1,'idol']]],
  ['cplex_48',['sudoku-cplex',['../example_mixed_integer_sudoku_cplex.html',1,'examples_mixed_integer']]],
  ['cplex_20glpk_20gurobi_20highs_20or_20any_20other_20solver_49',['Cannot find Cplex, GLPK, Gurobi, HiGHS, or any other solver',['../cannot_find_solver.html',1,'']]],
  ['create_20a_20build_20directory_50',['Step 2 — Create a build directory',['../build_from_source.html#step_build_dir',1,'']]],
  ['creating_20a_20branch_20and_20bound_20algorithm_51',['Creating a Branch-and-Bound Algorithm',['../lib_milp_branch_and_bound.html',1,'']]],
  ['creating_20multiple_20variables_20at_20once_52',['Creating Multiple Variables at Once',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_create_array',1,'']]],
  ['creating_20variables_53',['Creating Variables',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_create',1,'']]],
  ['creating_20your_20own_20optimizer_54',['Creating Your Own Optimizer',['../lib_milp_basics_advanced_create_optimizer.html',1,'lib_milp_basics']]],
  ['criticalvaluecolumnandconstraintgeneration_55',['CriticalValueColumnAndConstraintGeneration',['../classidol_1_1Optimizers_1_1Robust_1_1CriticalValueColumnAndConstraintGeneration.html',1,'idol::Optimizers::Robust::CriticalValueColumnAndConstraintGeneration'],['../classidol_1_1Robust_1_1CriticalValueColumnAndConstraintGeneration.html',1,'idol::Robust::CriticalValueColumnAndConstraintGeneration']]],
  ['ctr_56',['Ctr',['../classidol_1_1Ctr.html',1,'idol::Ctr'],['../classidol_1_1Ctr.html#a69a0cb3db3a3a73048288c7711849b93',1,'idol::Ctr::Ctr(Env &amp;t_env, TempCtr &amp;&amp;t_temp_ctr, std::string t_name=&quot;&quot;)'],['../classidol_1_1Ctr.html#a3f5753ff928dcea592a729c4a80c066f',1,'idol::Ctr::Ctr(Env &amp;t_env, const TempCtr &amp;t_temp_ctr, std::string t_name=&quot;&quot;)'],['../classidol_1_1Ctr.html#aee672fdead7ad11d9d6150e7c99f3145',1,'idol::Ctr::Ctr(Env &amp;t_env, CtrType t_type, double t_constant, std::string t_name=&quot;&quot;)']]],
  ['ctrbranchingdecision_57',['CtrBranchingDecision',['../structidol_1_1CtrBranchingDecision.html',1,'idol']]],
  ['ctrversion_58',['CtrVersion',['../classidol_1_1CtrVersion.html',1,'idol']]],
  ['cumulative_5fcount_59',['cumulative_count',['../classidol_1_1Timer.html#a807b77c2d7c3c6c22312ce88a6bf51bb',1,'idol::Timer']]],
  ['currentlypresentcut_60',['CurrentlyPresentCut',['../structidol_1_1CVCCG_1_1Formulation_1_1CurrentlyPresentCut.html',1,'idol::CVCCG::Formulation']]],
  ['currentpenalty_61',['CurrentPenalty',['../structidol_1_1ADM_1_1Formulation_1_1CurrentPenalty.html',1,'idol::ADM::Formulation']]],
  ['custom_20installation_20directory_62',['Custom installation directory',['../build_from_source.html#cmake_install_prefix',1,'']]],
  ['cut_20and_20price_63',['Cut and Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'About Branch-and-Cut-and-Price'],['../lib_milp_branch_and_price.html',1,'Branch-and-Cut-and-Price']]],
  ['cut_20generation_20library_20cgl_64',['Using the Coin-OR Cut Generation Library (Cgl)',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_cgl',1,'']]],
  ['cut_20pool_65',['The Cut Pool',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_cut_pool',1,'']]],
  ['cutfamily_66',['CutFamily',['../classidol_1_1CutFamily.html',1,'idol']]],
  ['cutpool_67',['CutPool',['../classidol_1_1CutPool.html',1,'idol']]],
  ['cuts_68',['Cuts',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_lazy_cuts',1,'Adding Your Own Lazy Cuts'],['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_user_cuts',1,'Adding Your Own User Cuts']]],
  ['cutting_20planes_69',['Cutting Planes',['../lib_milp_bnb_cutting_planes.html',1,'lib_milp_branch_and_bound']]]
];
