var searchData=
[
  ['padm_0',['PADM',['../classidol_1_1Bilevel_1_1PADM.html',1,'idol::Bilevel::PADM'],['../classidol_1_1Optimizers_1_1Bilevel_1_1PADM.html',1,'idol::Optimizers::Bilevel::PADM'],['../classidol_1_1Optimizers_1_1PADM.html',1,'idol::Optimizers::PADM'],['../classidol_1_1PADM.html',1,'idol::PADM']]],
  ['pair_1',['Pair',['../structidol_1_1Pair.html',1,'idol']]],
  ['pair_3c_20t_2c_20t_20_3e_2',['Pair&lt; T, T &gt;',['../structidol_1_1Pair.html',1,'idol']]],
  ['parallel_20pricing_3',['Parallel Pricing',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_parallel',1,'']]],
  ['param_4',['Param',['../classidol_1_1Param.html',1,'idol::Param'],['../classidol_1_1Param.html#abddc89cb7892eb4841efd6c219f8cfc1',1,'idol::Param::Param(const Var &amp;t_var)'],['../classidol_1_1Param.html#abd6102b12d3fccbf8ea7bdda12beda97',1,'idol::Param::Param(const Ctr &amp;t_ctr)'],['../classidol_1_1Param.html#aeaf61eb9ea6b75a37e0ff1554e24358b',1,'idol::Param::Param(const Param &amp;t_param)=default'],['../classidol_1_1Param.html#a7928ae7e1cd355ab0b3c5ef5442c8d68',1,'idol::Param::Param(Param &amp;&amp;t_param) noexcept=default']]],
  ['parameters_5',['Handling of Default Tolerances and Parameters',['../lib_milp_basics_advanced_environment.html#lib_milp_basics_advanced_environment_tolerances',1,'']]],
  ['party_20tools_6',['Third Party Tools',['../about.html#autotoc_md16',1,'']]],
  ['penaltymethod_7',['PenaltyMethod',['../classidol_1_1PenaltyMethod.html',1,'idol']]],
  ['penaltyupdate_8',['PenaltyUpdate',['../classidol_1_1PenaltyUpdate.html',1,'idol']]],
  ['pess_9',['zeng-pess',['../example_bilevel_zeng_pess.html',1,'examples_bilevel']]],
  ['pessimistic_20bilevel_20optimization_10',['Pessimistic bilevel optimization',['../examples_bilevel.html#examples_bilevel_mixed_integer_pessimistic',1,'']]],
  ['pessimistic_20bilevel_20problem_11',['Solving A Pessimistic Bilevel Problem',['../cli_bilevel_basics.html#cli_bilevel_basics_pessimistic',1,'']]],
  ['pessimisticasoptimistic_12',['PessimisticAsOptimistic',['../classidol_1_1Bilevel_1_1PessimisticAsOptimistic.html',1,'idol::Bilevel::PessimisticAsOptimistic'],['../classidol_1_1Optimizers_1_1Bilevel_1_1PessimisticAsOptimistic.html',1,'idol::Optimizers::Bilevel::PessimisticAsOptimistic']]],
  ['phase_20i_13',['Making the Master Problem Feasible (Phase I)',['../lib_milp_branch_and_price_cg_phaseI.html',1,'lib_milp_branch_and_price']]],
  ['phases_14',['Strong Branching with Phases',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_phases',1,'']]],
  ['planes_15',['Cutting Planes',['../lib_milp_bnb_cutting_planes.html',1,'lib_milp_branch_and_bound']]],
  ['point_16',['Point',['../classidol_1_1Point.html',1,'idol']]],
  ['point_3c_20ctr_20_3e_17',['Point&lt; Ctr &gt;',['../classidol_1_1Point.html',1,'idol']]],
  ['point_3c_20var_20_3e_18',['Point&lt; Var &gt;',['../classidol_1_1Point.html',1,'idol']]],
  ['pool_19',['The Cut Pool',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_cut_pool',1,'']]],
  ['pool_20clean_20up_20',['Column Pool Clean Up',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_clean_up',1,'']]],
  ['pool_20size_21',['Solution Pool Size',['../lib_milp_bnb_options.html#lib_milp_bnb_options_solution_pool',1,'']]],
  ['presolve_22',['Presolve',['../classidol_1_1Presolve.html',1,'idol::Presolve'],['../lib_milp_bnb_presolve.html',1,'Presolve']]],
  ['price_23',['Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'About Branch-and-Cut-and-Price'],['../lib_milp_branch_and_price.html',1,'Branch-and-Cut-and-Price']]],
  ['price_20algorithm_24',['Branch-and-price algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'']]],
  ['pricing_25',['Pricing',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_parallel',1,'Parallel Pricing'],['../lib_milp_branch_and_price_cg_HeuristicPricing.html',1,'Using Heuristics for Pricing']]],
  ['pricing_20callback_26',['Using Your Own Pricing Callback',['../lib_milp_branch_and_price_cg_callback.html',1,'lib_milp_branch_and_price']]],
  ['pricing_20problem_27',['Deriving the Pricing Problem',['../example_mixed_integer_gap_bap.html#autotoc_md5',1,'']]],
  ['primal_5fsolution_28',['primal_solution',['../classidol_1_1Callback.html#ac1a19a08051cc57531e9c14422a026c0',1,'idol::Callback']]],
  ['priorities_29',['Branching with Priorities',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_BranchingWithPriority',1,'']]],
  ['problem_30',['Problem',['../example_mixed_integer_gap_bap.html#autotoc_md5',1,'Deriving the Pricing Problem'],['../cli_bilevel_basics.html#cli_bilevel_basics_pessimistic',1,'Solving A Pessimistic Bilevel Problem'],['../cli_robust_basics.html#cli_robust_basics_aro_solving',1,'Solving a Two-Stage Robust Problem'],['../cli_bilevel_basics.html#cli_bilevel_basics_optimistic',1,'Solving An Optimistic Bilevel Problem']]],
  ['problem_20feasible_20phase_20i_31',['Making the Master Problem Feasible (Phase I)',['../lib_milp_branch_and_price_cg_phaseI.html',1,'lib_milp_branch_and_price']]],
  ['problems_32',['Basics of the Command Line Interface for Robust Problems',['../cli_robust_basics.html',1,'']]],
  ['problems_20via_20its_20kkt_20based_20single_20level_20reformulation_33',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['product_34',['Product',['../classidol_1_1NodeScoreFunctions_1_1Product.html',1,'idol::NodeScoreFunctions']]],
  ['providing_20bounds_20on_20the_20dual_20variables_35',['The File Format for Providing Bounds on the Dual Variables',['../cli_bilevel_kkt.html#kkt_big_m_file',1,'']]],
  ['pseudo_20cost_20branching_36',['Pseudo Cost Branching',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_PseudoCost',1,'']]],
  ['pseudocost_37',['PseudoCost',['../classidol_1_1BranchingRules_1_1PseudoCost.html',1,'idol::BranchingRules::PseudoCost&lt; NodeInfoT &gt;'],['../classidol_1_1PseudoCost.html',1,'idol::PseudoCost']]]
];
