var searchData=
[
  ['bab_0',['flp-bab',['../example_mixed_integer_flp_bab.html',1,'examples_mixed_integer']]],
  ['bap_1',['bap',['../example_mixed_integer_bin_bap.html',1,'bin-bap'],['../example_mixed_integer_gap_bap.html',1,'gap-bap'],['../example_mixed_integer_rspp_bap.html',1,'rspp-bap']]],
  ['bard_20mibs_2',['moore-bard-mibs',['../example_bilevel_moore_bard_mibs.html',1,'examples_bilevel']]],
  ['based_20single_20level_20reformulation_3',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['basics_4',['Basics',['../lib_milp_basics.html',1,'Basics'],['../lib_milp_branch_and_bound.html#lib_milp_bnb_basics',1,'Basics']]],
  ['basics_20of_20the_20command_20line_20interface_20for_20bilevel_20optimization_5',['Basics of the Command Line Interface for Bilevel Optimization',['../cli_bilevel_basics.html',1,'']]],
  ['basics_20of_20the_20command_20line_20interface_20for_20milps_6',['Basics of the Command Line Interface for MILPs',['../cli_milp_basics.html',1,'']]],
  ['basics_20of_20the_20command_20line_20interface_20for_20robust_20problems_7',['Basics of the Command Line Interface for Robust Problems',['../cli_robust_basics.html',1,'']]],
  ['best_20bound_8',['Best Bound',['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_BestBound',1,'']]],
  ['best_20estimate_9',['Best Estimate',['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_BestEstimate',1,'']]],
  ['best_5fbound_10',['best_bound',['../classidol_1_1Callback.html#aec34a610d1edb398e806774b2ead856e',1,'idol::Callback']]],
  ['best_5fobj_11',['best_obj',['../classidol_1_1Callback.html#ab45dfb3e9f7155de67fceb474a0dd827',1,'idol::Callback']]],
  ['bestbound_12',['BestBound',['../classidol_1_1BestBound.html',1,'idol::BestBound'],['../classidol_1_1NodeSelectionRules_1_1BestBound.html',1,'idol::NodeSelectionRules::BestBound&lt; NodeT &gt;']]],
  ['bestestimate_13',['BestEstimate',['../classidol_1_1BestEstimate.html',1,'idol::BestEstimate'],['../classidol_1_1NodeSelectionRules_1_1BestEstimate.html',1,'idol::NodeSelectionRules::BestEstimate&lt; NodeT &gt;']]],
  ['big_20m_20reformulation_14',['Using the Big-M Reformulation',['../cli_bilevel_kkt.html#kkt_big_m',1,'']]],
  ['bigmfreeseparation_15',['BigMFreeSeparation',['../classidol_1_1Robust_1_1CCG_1_1BigMFreeSeparation.html',1,'idol::Robust::CCG']]],
  ['bilevel_20optimization_16',['Bilevel Optimization',['../cli_bilevel_basics.html',1,'Basics of the Command Line Interface for Bilevel Optimization'],['../cli_tutorials.html#cli_tutorials_bilevel',1,'Bilevel Optimization']]],
  ['bilevel_20optimization_17',['Bilevel optimization',['../examples_bilevel.html',1,'Bilevel optimization'],['../stable_features_bilevel.html',1,'Bilevel optimization']]],
  ['bilevel_20optimization_18',['bilevel optimization',['../examples_bilevel.html#examples_bilevel_continuous',1,'Continuous bilevel optimization'],['../examples_bilevel.html#examples_bilevel_mixed_integer',1,'Mixed-integer bilevel optimization'],['../examples_bilevel.html#examples_bilevel_mixed_integer_pessimistic',1,'Pessimistic bilevel optimization']]],
  ['bilevel_20problem_19',['Bilevel Problem',['../cli_bilevel_basics.html#cli_bilevel_basics_pessimistic',1,'Solving A Pessimistic Bilevel Problem'],['../cli_bilevel_basics.html#cli_bilevel_basics_optimistic',1,'Solving An Optimistic Bilevel Problem']]],
  ['bilevel_20problems_20via_20its_20kkt_20based_20single_20level_20reformulation_20',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['bin_20bap_21',['bin-bap',['../example_mixed_integer_bin_bap.html',1,'examples_mixed_integer']]],
  ['bound_22',['Bound',['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_BestBound',1,'Best Bound'],['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_WorstBound',1,'Worst Bound']]],
  ['bound_20algorithm_23',['Creating a Branch-and-Bound Algorithm',['../lib_milp_branch_and_bound.html',1,'']]],
  ['bound_20algorithm_24',['Branch-and-bound algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'']]],
  ['bound_20rounding_25',['Bound Rounding',['../lib_milp_bnb_presolve.html#lib_milp_bnb_presolve_BoundRounding',1,'']]],
  ['bound_20specific_20callback_26',['Writing a Branch-and-Bound-Specific Callback',['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_specific',1,'']]],
  ['bound_20strengthening_27',['One Row Bound Strengthening',['../lib_milp_bnb_presolve.html#lib_milp_bnb_presolve_OneRowBoundStrengthening',1,'']]],
  ['boundprovider_28',['BoundProvider',['../classidol_1_1Reformulators_1_1KKT_1_1BoundProvider.html',1,'idol::Reformulators::KKT::BoundProvider'],['../classidol_1_1Robust_1_1CCG_1_1BigMFreeSeparation_1_1BoundProvider.html',1,'idol::Robust::CCG::BigMFreeSeparation::BoundProvider']]],
  ['boundprovidermap_29',['BoundProviderMap',['../classidol_1_1Reformulators_1_1KKT_1_1BoundProviderMap.html',1,'idol::Reformulators::KKT']]],
  ['boundrounding_30',['BoundRounding',['../classidol_1_1Presolvers_1_1BoundRounding.html',1,'idol::Presolvers']]],
  ['bounds_31',['Reference for Dual Variable Bounds',['../cli_bilevel_kkt.html#kkt_big_m_def',1,'']]],
  ['bounds_20on_20the_20dual_20variables_32',['The File Format for Providing Bounds on the Dual Variables',['../cli_bilevel_kkt.html#kkt_big_m_file',1,'']]],
  ['branch_20and_20bound_20algorithm_33',['Creating a Branch-and-Bound Algorithm',['../lib_milp_branch_and_bound.html',1,'']]],
  ['branch_20and_20bound_20algorithm_34',['Branch-and-bound algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'']]],
  ['branch_20and_20bound_20specific_20callback_35',['Writing a Branch-and-Bound-Specific Callback',['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_specific',1,'']]],
  ['branch_20and_20cut_20and_20price_36',['Branch and Cut and Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'About Branch-and-Cut-and-Price'],['../lib_milp_branch_and_price.html',1,'Branch-and-Cut-and-Price']]],
  ['branch_20and_20price_20algorithm_37',['Branch-and-Price algorithm',['../example_mixed_integer_rspp_bap.html#autotoc_md8',1,'']]],
  ['branch_20and_20price_20algorithm_38',['Branch-and-price algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'']]],
  ['branchandbound_39',['BranchAndBound',['../classidol_1_1BranchAndBound.html',1,'idol::BranchAndBound&lt; NodeT &gt;'],['../classidol_1_1Optimizers_1_1BranchAndBound.html',1,'idol::Optimizers::BranchAndBound&lt; NodeInfoT &gt;'],['../classidol_1_1BranchAndBound.html#a96fec5e9e6f278c51ec788b317321616',1,'idol::BranchAndBound::BranchAndBound()=default'],['../classidol_1_1BranchAndBound.html#a15e010f0ecbb6ddde4ec3fee723564f0',1,'idol::BranchAndBound::BranchAndBound(const BranchAndBound &amp;t_rhs)']]],
  ['branchandbound_3c_20nodet_20_3e_40',['BranchAndBound&lt; NodeT &gt;',['../classidol_1_1Optimizers_1_1BranchAndBound.html',1,'idol::Optimizers']]],
  ['branchandboundcallback_41',['BranchAndBoundCallback',['../classidol_1_1BranchAndBoundCallback.html',1,'idol']]],
  ['branchandboundcallbackfactory_42',['BranchAndBoundCallbackFactory',['../classidol_1_1BranchAndBoundCallbackFactory.html',1,'idol']]],
  ['branchandboundcallbackfactory_3c_20idol_3a_3adefaultnodeinfo_20_3e_43',['BranchAndBoundCallbackFactory&lt; idol::DefaultNodeInfo &gt;',['../classidol_1_1BranchAndBoundCallbackFactory.html',1,'idol']]],
  ['branchandboundcallbacki_44',['BranchAndBoundCallbackI',['../classidol_1_1BranchAndBoundCallbackI.html',1,'idol']]],
  ['branchandcut_45',['BranchAndCut',['../classidol_1_1Bilevel_1_1BranchAndCut.html',1,'idol::Bilevel::BranchAndCut'],['../classidol_1_1Optimizers_1_1Bilevel_1_1BranchAndCut.html',1,'idol::Optimizers::Bilevel::BranchAndCut']]],
  ['branching_46',['Branching',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_bnb',1,'Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_full',1,'Full Strong Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_PseudoCost',1,'Pseudo Cost Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_restricted',1,'Restricted Strong Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching',1,'Strong Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_UniformlyRandom',1,'Uniformly Random Branching']]],
  ['branching_20rule_47',['Writing Your Own Branching Rule',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_writing',1,'']]],
  ['branching_20rules_48',['Branching Rules',['../lib_milp_bnb_branching_rule.html',1,'lib_milp_branch_and_bound']]],
  ['branching_20with_20look_20ahead_49',['Strong Branching with Look Ahead',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_look_ahead',1,'']]],
  ['branching_20with_20phases_50',['Strong Branching with Phases',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_phases',1,'']]],
  ['branching_20with_20priorities_51',['Branching with Priorities',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_BranchingWithPriority',1,'']]],
  ['branchingrule_52',['BranchingRule',['../classidol_1_1BranchingRule.html',1,'idol']]],
  ['branchingrulefactory_53',['BranchingRuleFactory',['../classidol_1_1BranchingRuleFactory.html',1,'idol']]],
  ['branchingrulefactory_3c_20idol_3a_3adefaultnodeinfo_20_3e_54',['BranchingRuleFactory&lt; idol::DefaultNodeInfo &gt;',['../classidol_1_1BranchingRuleFactory.html',1,'idol']]],
  ['branchingrulefactory_3c_20nodeinfot_20_3e_55',['BranchingRuleFactory&lt; NodeInfoT &gt;',['../classidol_1_1BranchingRuleFactory.html',1,'idol']]],
  ['branchingwithpriority_56',['BranchingWithPriority',['../classidol_1_1BranchingRules_1_1BranchingWithPriority.html',1,'idol::BranchingRules::BranchingWithPriority&lt; NodeInfoT &gt;'],['../classidol_1_1BranchingWithPriority.html',1,'idol::BranchingWithPriority&lt; NodeT &gt;']]],
  ['breadth_20first_57',['Breadth First',['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_BreadthFirst',1,'']]],
  ['breadthfirst_58',['BreadthFirst',['../classidol_1_1BreadthFirst.html',1,'idol::BreadthFirst'],['../classidol_1_1NodeSelectionRules_1_1BreadthFirst.html',1,'idol::NodeSelectionRules::BreadthFirst&lt; NodeT &gt;']]],
  ['build_59',['Step 3 — Configure and build',['../build_from_source.html#step_configure',1,'']]],
  ['build_20directory_60',['Step 2 — Create a build directory',['../build_from_source.html#step_build_dir',1,'']]],
  ['build_20examples_61',['Build examples',['../build_from_source.html#cmake_examples',1,'']]],
  ['build_20from_20source_62',['Build from source',['../build_from_source.html',1,'']]],
  ['build_20instructions_63',['Build instructions',['../build_from_source.html#build_steps',1,'']]],
  ['build_20tests_64',['Build tests',['../build_from_source.html#cmake_tests',1,'']]],
  ['building_20and_20solving_20simple_20models_65',['Building and solving simple models',['../examples_mixed_integer.html#examples_mixed_integer_modeling',1,'']]]
];
