var searchData=
[
  ['dantzig_20wolfe_20decomposition_0',['Dantzig Wolfe Decomposition',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_cg',1,'About Dantzig-Wolfe Decomposition'],['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_dantzig_wolfe',1,'Using the Dantzig-Wolfe Decomposition']]],
  ['dantzig_20wolfe_20reformulation_1',['Dantzig Wolfe Reformulation',['../example_mixed_integer_bin_bap.html#autotoc_md1',1,'Dantzig-Wolfe Reformulation'],['../example_mixed_integer_gap_bap.html#autotoc_md4',1,'Dantzig-Wolfe Reformulation']]],
  ['dantzigwolfedecomposition_2',['DantzigWolfeDecomposition',['../classidol_1_1DantzigWolfeDecomposition.html',1,'idol::DantzigWolfeDecomposition'],['../classidol_1_1Optimizers_1_1DantzigWolfeDecomposition.html',1,'idol::Optimizers::DantzigWolfeDecomposition']]],
  ['deactivating_20kleinart_20et_20al_202020_20valid_20inequalities_3',['Deactivating Kleinart et al. (2020) Valid Inequalities',['../cli_bilevel_kkt.html#kkt_kleinert_vi',1,'']]],
  ['decision_20variables_4',['Decision Variables',['../example_mixed_integer_tsp_gurobi.html#autotoc_md8',1,'']]],
  ['decomposition_5',['Decomposition',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_cg',1,'About Dantzig-Wolfe Decomposition'],['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_dantzig_wolfe',1,'Using the Dantzig-Wolfe Decomposition']]],
  ['default_20tolerances_20and_20parameters_6',['Handling of Default Tolerances and Parameters',['../lib_milp_basics_advanced_environment.html#lib_milp_basics_advanced_environment_tolerances',1,'']]],
  ['defaultnodeinfo_7',['DefaultNodeInfo',['../classidol_1_1DefaultNodeInfo.html',1,'idol']]],
  ['defaultnodeupdator_8',['DefaultNodeUpdator',['../classidol_1_1DefaultNodeUpdator.html',1,'idol']]],
  ['degree_20constraints_9',['Degree Constraints',['../example_mixed_integer_tsp_gurobi.html#autotoc_md10',1,'']]],
  ['depth_20first_10',['Depth First',['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_DepthFirst',1,'']]],
  ['depthfirst_11',['DepthFirst',['../classidol_1_1DepthFirst.html',1,'idol::DepthFirst'],['../classidol_1_1NodeSelectionRules_1_1DepthFirst.html',1,'idol::NodeSelectionRules::DepthFirst&lt; NodeT &gt;']]],
  ['deriving_20the_20pricing_20problem_12',['Deriving the Pricing Problem',['../example_mixed_integer_gap_bap.html#autotoc_md5',1,'']]],
  ['description_13',['Description',['../classidol_1_1Bilevel_1_1Description.html',1,'idol::Bilevel::Description'],['../classidol_1_1Robust_1_1Description.html',1,'idol::Robust::Description'],['../cli_bilevel_basics.html#cli_bilevel_basics_input_details',1,'Detailed Description'],['../cli_robust_basics.html#cli_robust_basics_input_detailed',1,'Detailed Description'],['../cli_robust_basics.html#cli_robust_basics_aro_input_detailed',1,'Detailed Description']]],
  ['desiredspec_14',['DesiredSpec',['../structidol_1_1Problems_1_1Counterfactual_1_1Instance_1_1DesiredSpec.html',1,'idol::Problems::Counterfactual::Instance']]],
  ['detailed_20description_15',['Detailed Description',['../cli_bilevel_basics.html#cli_bilevel_basics_input_details',1,'Detailed Description'],['../cli_robust_basics.html#cli_robust_basics_input_detailed',1,'Detailed Description'],['../cli_robust_basics.html#cli_robust_basics_aro_input_detailed',1,'Detailed Description']]],
  ['dim_16',['Dim',['../classidol_1_1Dim.html',1,'idol']]],
  ['directory_17',['directory',['../build_from_source.html#cmake_install_prefix',1,'Custom installation directory'],['../build_from_source.html#step_build_dir',1,'Step 2 — Create a build directory']]],
  ['diver_18',['Diver',['../classidol_1_1BranchingRules_1_1Diver.html',1,'idol::BranchingRules::Diver&lt; BranchingRuleT &gt;'],['../classidol_1_1Diver.html',1,'idol::Diver&lt; BranchingRuleT &gt;']]],
  ['do_20with_20it_19',['What is a Model and What Can You Do with It?',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_what',1,'']]],
  ['download_20using_20cmake_20fetchcontent_20',['Automatic Download using CMake &lt;span class=&quot;tt&quot;&gt;FetchContent&lt;/span&gt;',['../lib_installation.html#lib_install_cmake',1,'']]],
  ['dual_21',['lp-dual',['../example_mixed_integer_lp_dual.html',1,'examples_mixed_integer']]],
  ['dual_20variable_20bounds_22',['Reference for Dual Variable Bounds',['../cli_bilevel_kkt.html#kkt_big_m_def',1,'']]],
  ['dual_20variables_23',['The File Format for Providing Bounds on the Dual Variables',['../cli_bilevel_kkt.html#kkt_big_m_file',1,'']]],
  ['dualize_24',['Dualize',['../classidol_1_1Bilevel_1_1MinMax_1_1Dualize.html',1,'idol::Bilevel::MinMax::Dualize'],['../classidol_1_1Optimizers_1_1Bilevel_1_1MinMax_1_1Dualize.html',1,'idol::Optimizers::Bilevel::MinMax::Dualize']]],
  ['dualpricesmoothingstabilization_25',['DualPriceSmoothingStabilization',['../classidol_1_1DantzigWolfe_1_1DualPriceSmoothingStabilization.html',1,'idol::DantzigWolfe']]],
  ['dynamiclib_26',['DynamicLib',['../classidol_1_1Optimizers_1_1GLPK_1_1DynamicLib.html',1,'idol::Optimizers::GLPK::DynamicLib'],['../classidol_1_1Optimizers_1_1Gurobi_1_1DynamicLib.html',1,'idol::Optimizers::Gurobi::DynamicLib'],['../classidol_1_1Optimizers_1_1HiGHS_1_1DynamicLib.html',1,'idol::Optimizers::HiGHS::DynamicLib']]]
];
