var searchData=
[
  ['id_0',['id',['../classidol_1_1Param.html#a41243b2248da219ea1467bb0898e025a',1,'idol::Param::id()'],['../classidol_1_1Object.html#ac8e398b9b937f08b1c5dbd2b32414036',1,'idol::Object::id()']]],
  ['identity_1',['identity',['../structidol_1_1identity.html',1,'idol']]],
  ['idol_2',['idol',['../index.html#getting_started_with_idol',1,'Getting Started with idol'],['../index.html#what_is_idol',1,'What is idol?']]],
  ['idol_3a_3atolerance_3',['Tolerance',['../namespaceidol_1_1Tolerance.html',1,'idol']]],
  ['infeasibilitystrategyfactory_4',['InfeasibilityStrategyFactory',['../classidol_1_1DantzigWolfe_1_1InfeasibilityStrategyFactory.html',1,'idol::DantzigWolfe']]],
  ['info_5',['info',['../classidol_1_1Logs_1_1BranchAndBound_1_1Info.html',1,'idol::Logs::BranchAndBound::Info&lt; NodeInfoT &gt;'],['../classidol_1_1Logs_1_1DantzigWolfe_1_1Info.html',1,'idol::Logs::DantzigWolfe::Info']]],
  ['initialize_6',['initialize',['../classidol_1_1Cuts_1_1KnapsackCover_1_1Strategy.html#ac3b637513554dd08621768a8dfd79dff',1,'idol::Cuts::KnapsackCover::Strategy::initialize()'],['../classidol_1_1BranchAndBoundCallback.html#acfa261050e03bf300457218a38be51d6',1,'idol::BranchAndBoundCallback::initialize()']]],
  ['installation_7',['Installation',['../manual-installation.html#autotoc_md7',1,'']]],
  ['installation_20from_20source_8',['Installation from source',['../manual-installation.html',1,'installation']]],
  ['installation_20guidelines_9',['Installation guidelines',['../installation.html',1,'']]],
  ['installation_20with_20cmake_10',['Automatic installation with CMake',['../automatic-installation.html',1,'installation']]],
  ['instance_11',['instance',['../classidol_1_1Problems_1_1FLP_1_1Instance.html',1,'idol::Problems::FLP::Instance'],['../classidol_1_1Problems_1_1SRP_1_1Instance.html',1,'idol::Problems::SRP::Instance'],['../classidol_1_1Problems_1_1MKP_1_1Instance.html',1,'idol::Problems::MKP::Instance'],['../classidol_1_1Problems_1_1KP_1_1Instance.html',1,'idol::Problems::KP::Instance'],['../classidol_1_1Problems_1_1GAP_1_1Instance.html',1,'idol::Problems::GAP::Instance']]],
  ['integer_12',['Integer',['../namespaceidol_1_1Tolerance.html#abc666019c56885dd181bef0e1ce49088',1,'idol::Tolerance']]],
  ['integer_20bilevel_20optimization_13',['Mixed-integer bilevel optimization',['../examples_bilevel.html#examples_bilevel_mixed_integer',1,'']]],
  ['integer_20optimization_14',['integer optimization',['../stable_features_mixed_integer.html',1,'Mixed-integer optimization'],['../examples_mixed_integer.html',1,'Mixed-integer optimization']]],
  ['integermaster_15',['IntegerMaster',['../classidol_1_1Heuristics_1_1IntegerMaster.html',1,'idol::Heuristics']]],
  ['interface_16',['Modeling interface',['../test_modeling_interface.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20clp_20via_20osi_17',['Interfacing Clp via Osi',['../test_wrapper_OsiClp.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20cplex_18',['Interfacing Cplex',['../test_wrapper_Cplex.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20cplex_20via_20osi_19',['Interfacing Cplex via Osi',['../test_wrapper_OsiCplex.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20glpk_20',['Interfacing GLPK',['../test_wrapper_GLPK.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20gurobi_21',['Interfacing Gurobi',['../test_wrapper_Gurobi.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20highs_22',['Interfacing HiGHS',['../test_wrapper_HiGHS.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20jump_23',['Interfacing JuMP',['../test_wrapper_JuMP.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20mibs_24',['Interfacing MibS',['../test_wrapper_MibS.html',1,'stable_features_bilevel']]],
  ['interfacing_20mosek_25',['Interfacing Mosek',['../test_wrapper_Mosek.html',1,'stable_features_mixed_integer']]],
  ['is_26',['is',['../classidol_1_1Param.html#a3a60236e5a635f6611c172b74777d93a',1,'idol::Param']]],
  ['is_20idol_27',['What is idol?',['../index.html#what_is_idol',1,'']]],
  ['is_20this_20a_20mip_20solver_28',['Is this a MIP Solver?',['../index.html#is_this_a_mip_solver',1,'']]],
  ['is_5fin_29',['is_in',['../classidol_1_1Object.html#aa25899704860cb066f885015ec1f11f3',1,'idol::Object']]],
  ['item_30',['Item',['../structidol_1_1Cuts_1_1KnapsackCover_1_1Strategy_1_1KnapsackStructure_1_1Item.html',1,'idol::Cuts::KnapsackCover::Strategy::KnapsackStructure']]],
  ['iterationplot_31',['IterationPlot',['../classidol_1_1Optimizers_1_1PADM_1_1IterationPlot.html',1,'idol::Optimizers::PADM']]],
  ['iterator_32',['iterator',['../classidol_1_1Range_1_1iterator.html',1,'idol::Range']]],
  ['iteratorforward_33',['IteratorForward',['../classidol_1_1IteratorForward.html',1,'idol']]]
];
