var searchData=
[
  ['a_20branch_20and_20bound_20algorithm_0',['Creating a Branch-and-Bound Algorithm',['../lib_milp_branch_and_bound.html',1,'']]],
  ['a_20branch_20and_20bound_20specific_20callback_1',['Writing a Branch-and-Bound-Specific Callback',['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_specific',1,'']]],
  ['a_20build_20directory_2',['Step 2 — Create a build directory',['../build_from_source.html#step_build_dir',1,'']]],
  ['a_20first_20example_3',['A First Example',['../cli_bilevel_basics.html#cli_bilevel_basics_input_example',1,'A First Example'],['../cli_robust_basics.html#cli_robust_basics_input_example',1,'A First Example'],['../cli_robust_basics.html#cli_robust_basics_aro_input_example',1,'A First Example']]],
  ['a_20mip_20solver_4',['Is this a MIP Solver?',['../index.html#is_this_a_mip_solver',1,'']]],
  ['a_20model_20and_20what_20can_20you_20do_20with_20it_5',['What is a Model and What Can You Do with It?',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_what',1,'']]],
  ['a_20pessimistic_20bilevel_20problem_6',['Solving A Pessimistic Bilevel Problem',['../cli_bilevel_basics.html#cli_bilevel_basics_pessimistic',1,'']]],
  ['a_20toy_20example_7',['A Toy Example',['../lib_milp_basics.html#lib_milp_basics_hello_world',1,'']]],
  ['a_20two_20stage_20robust_20problem_8',['Solving a Two-Stage Robust Problem',['../cli_robust_basics.html#cli_robust_basics_aro_solving',1,'']]],
  ['a_20universal_20callback_9',['Writing a Universal Callback',['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_universal',1,'']]],
  ['about_10',['About',['../about.html',1,'']]],
  ['about_20branch_20and_20cut_20and_20price_11',['About Branch-and-Cut-and-Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'']]],
  ['about_20dantzig_20wolfe_20decomposition_12',['About Dantzig-Wolfe Decomposition',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_cg',1,'']]],
  ['abstractbranchandboundcallbacki_13',['AbstractBranchAndBoundCallbackI',['../classidol_1_1AbstractBranchAndBoundCallbackI.html',1,'idol']]],
  ['abstractpresolver_14',['AbstractPresolver',['../classidol_1_1Presolvers_1_1AbstractPresolver.html',1,'idol::Presolvers']]],
  ['accessing_20variables_15',['Accessing Variables',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_access',1,'']]],
  ['adaptive_16',['Adaptive',['../classidol_1_1PenaltyUpdates_1_1Adaptive.html',1,'idol::PenaltyUpdates']]],
  ['add_5fcallback_17',['add_callback',['../classidol_1_1BranchAndBound.html#a946aaee3c50f86c76c45e245dcf77148',1,'idol::BranchAndBound::add_callback(const BranchAndBoundCallbackFactory&lt; NodeT &gt; &amp;t_callback)'],['../classidol_1_1BranchAndBound.html#aa02f32f7120d917e8b843d0b280fcd2a',1,'idol::BranchAndBound::add_callback(const CallbackFactory &amp;t_callback)']]],
  ['add_5fcoupling_18',['add_coupling',['../classidol_1_1Reformulators_1_1KKT.html#af5817234f776d003cbb03ca57bf33ef3',1,'idol::Reformulators::KKT']]],
  ['add_5fdual_19',['add_dual',['../classidol_1_1Reformulators_1_1KKT.html#ae1915c072528d0075956bc8a3e3105c9',1,'idol::Reformulators::KKT']]],
  ['add_5fkkt_5freformulation_20',['add_kkt_reformulation',['../classidol_1_1Reformulators_1_1KKT.html#a45696c704e7817d0dab3526028e32cc1',1,'idol::Reformulators::KKT']]],
  ['add_5flazy_5fcut_21',['add_lazy_cut',['../classidol_1_1BranchAndBoundCallback.html#a3bfb09e103d540c1bf8a1abff252cd04',1,'idol::BranchAndBoundCallback::add_lazy_cut()'],['../classidol_1_1Callback.html#a551ffb69f6115fad4f91974e2da45ed4',1,'idol::Callback::add_lazy_cut()']]],
  ['add_5fprimal_22',['add_primal',['../classidol_1_1Reformulators_1_1KKT.html#a3105c9f4dad9c492a070f7acddb8f821',1,'idol::Reformulators::KKT']]],
  ['add_5fstrong_5fduality_5freformulation_23',['add_strong_duality_reformulation',['../classidol_1_1Reformulators_1_1KKT.html#a4377296c673a4ec8ed458c8852d6dc14',1,'idol::Reformulators::KKT']]],
  ['add_5fuser_5fcut_24',['add_user_cut',['../classidol_1_1BranchAndBoundCallback.html#a232c9cf4520ea95bbd142fd56959ef1b',1,'idol::BranchAndBoundCallback::add_user_cut()'],['../classidol_1_1Callback.html#acb1781b217b4d14b307ff8b74a535bdf',1,'idol::Callback::add_user_cut()']]],
  ['adding_20your_20own_20lazy_20cuts_25',['Adding Your Own Lazy Cuts',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_lazy_cuts',1,'']]],
  ['adding_20your_20own_20user_20cuts_26',['Adding Your Own User Cuts',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_user_cuts',1,'']]],
  ['additive_27',['Additive',['../classidol_1_1PenaltyUpdates_1_1Additive.html',1,'idol::PenaltyUpdates']]],
  ['advanced_20features_28',['More advanced features',['../examples_mixed_integer.html#examples_mixed_integer_mored_advanced_features',1,'']]],
  ['advanced_20topics_29',['Advanced Topics',['../lib_milp_basics.html#lib_milp_basics_advanced',1,'More Advanced Topics'],['../lib_milp_branch_and_bound.html#lib_milp_bnb_sub_pages',1,'More Advanced Topics'],['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced',1,'More Advanced Topics']]],
  ['affexpr_30',['AffExpr',['../classidol_1_1AffExpr.html',1,'idol']]],
  ['affexpr_3c_20idol_3a_3avar_20_3e_31',['AffExpr&lt; idol::Var &gt;',['../classidol_1_1AffExpr.html',1,'idol']]],
  ['affexpr_3c_20idol_3a_3avar_2c_20double_20_3e_32',['AffExpr&lt; idol::Var, double &gt;',['../classidol_1_1AffExpr.html',1,'idol']]],
  ['affexpr_3c_20idol_3a_3avar_2c_20idol_3a_3aquadexpr_3c_20idol_3a_3avar_20_3e_20_3e_33',['AffExpr&lt; idol::Var, idol::QuadExpr&lt; idol::Var &gt; &gt;',['../classidol_1_1AffExpr.html',1,'idol']]],
  ['ahead_34',['Strong Branching with Look Ahead',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_look_ahead',1,'']]],
  ['al_202020_20valid_20inequalities_35',['Deactivating Kleinart et al. (2020) Valid Inequalities',['../cli_bilevel_kkt.html#kkt_kleinert_vi',1,'']]],
  ['algorithm_36',['Algorithm',['../classidol_1_1Algorithm.html',1,'idol::Algorithm'],['../lib_milp_branch_and_bound.html',1,'Creating a Branch-and-Bound Algorithm']]],
  ['algorithm_37',['algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'Branch-and-bound algorithm'],['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'Branch-and-price algorithm']]],
  ['amd64_38',['amd64',['../cli_installation.html#linux',1,'Linux (amd64)'],['../lib_installation.html#lib_install_linux',1,'Linux (amd64)']]],
  ['an_20exponential_20size_20model_39',['An Exponential-Size Model',['../example_mixed_integer_tsp_gurobi.html#autotoc_md7',1,'']]],
  ['an_20external_20solver_40',['Using an External Solver',['../lib_milp_basics.html#lib_milp_basics_solving',1,'']]],
  ['an_20optimistic_20bilevel_20problem_41',['Solving An Optimistic Bilevel Problem',['../cli_bilevel_basics.html#cli_bilevel_basics_optimistic',1,'']]],
  ['an_20optimization_20environment_42',['What is an Optimization Environment',['../lib_milp_basics_advanced_environment.html#lib_milp_basics_advanced_environment_what',1,'']]],
  ['and_20bound_20algorithm_43',['Creating a Branch-and-Bound Algorithm',['../lib_milp_branch_and_bound.html',1,'']]],
  ['and_20bound_20algorithm_44',['Branch-and-bound algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'']]],
  ['and_20bound_20specific_20callback_45',['Writing a Branch-and-Bound-Specific Callback',['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_specific',1,'']]],
  ['and_20build_46',['Step 3 — Configure and build',['../build_from_source.html#step_configure',1,'']]],
  ['and_20cut_20and_20price_47',['and Cut and Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'About Branch-and-Cut-and-Price'],['../lib_milp_branch_and_price.html',1,'Branch-and-Cut-and-Price']]],
  ['and_20moving_20models_48',['Copying and Moving Models',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_copy',1,'']]],
  ['and_20mps_49',['Example (.lp and .mps)',['../cli_milp_basics.html#cli_milp_example_lp',1,'']]],
  ['and_20optimizer_20factories_50',['Optimizers and Optimizer Factories',['../lib_milp_basics_advanced_optimizers.html',1,'lib_milp_basics']]],
  ['and_20parameters_51',['Handling of Default Tolerances and Parameters',['../lib_milp_basics_advanced_environment.html#lib_milp_basics_advanced_environment_tolerances',1,'']]],
  ['and_20price_52',['and Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'About Branch-and-Cut-and-Price'],['../lib_milp_branch_and_price.html',1,'Branch-and-Cut-and-Price']]],
  ['and_20price_20algorithm_53',['Branch-and-price algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'']]],
  ['and_20solving_20simple_20models_54',['Building and solving simple models',['../examples_mixed_integer.html#examples_mixed_integer_modeling',1,'']]],
  ['and_20what_20can_20you_20do_20with_20it_55',['What is a Model and What Can You Do with It?',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_what',1,'']]],
  ['annotation_56',['Annotation',['../classidol_1_1Annotation.html',1,'idol']]],
  ['annotation_3c_20double_20_3e_57',['Annotation&lt; double &gt;',['../classidol_1_1Annotation.html',1,'idol']]],
  ['annotation_3c_20unsigned_20int_20_3e_58',['Annotation&lt; unsigned int &gt;',['../classidol_1_1Annotation.html',1,'idol']]],
  ['any_20other_20solver_59',['Cannot find Cplex, GLPK, Gurobi, HiGHS, or any other solver',['../cannot_find_solver.html',1,'']]],
  ['arm64_60',['arm64',['../cli_installation.html#mac',1,'MacOs (arm64)'],['../lib_installation.html#lib_install_mac',1,'MacOs (arm64)']]],
  ['artificialcosts_61',['ArtificialCosts',['../classidol_1_1DantzigWolfe_1_1ArtificialCosts.html',1,'idol::DantzigWolfe']]],
  ['as_62',['as',['../classidol_1_1Param.html#a219e93e421a4cb640896c8e9a73cfea7',1,'idol::Param']]],
  ['at_20once_63',['Creating Multiple Variables at Once',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_create_array',1,'']]],
  ['author_64',['Author',['../about.html#autotoc_md18',1,'']]],
  ['automatic_20download_20using_20cmake_20fetchcontent_65',['Automatic Download using CMake &lt;span class=&quot;tt&quot;&gt;FetchContent&lt;/span&gt;',['../lib_installation.html#lib_install_cmake',1,'']]],
  ['aux_20file_66',['Format of the &lt;span class=&quot;tt&quot;&gt;.aux&lt;/span&gt; File',['../cli_bilevel_basics.html#cli_bilevel_aux',1,'']]]
];
