var searchData=
[
  ['scoring_20function_0',['Changing the Scoring Function',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_scoring',1,'']]],
  ['selection_20rule_1',['Writing Your Own Node Selection Rule',['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_writing',1,'']]],
  ['selection_20rules_2',['Node Selection Rules',['../lib_milp_bnb_node_selection.html',1,'lib_milp_branch_and_bound']]],
  ['separation_3',['Separation',['../classidol_1_1Robust_1_1CCG_1_1Separation.html',1,'idol::Robust::CCG::Separation'],['../lib_milp_branch_and_price_cg_in_out.html',1,'Stabilizing Column Generation via in-out Separation']]],
  ['set_4',['set',['../classidol_1_1Object.html#a7d1921eca2bb0e0453867839e80dde63',1,'idol::Object']]],
  ['set_5flb_5',['set_lb',['../classidol_1_1TempVar.html#a0f437cb9e1aa828b263be4e09b7fe0c2',1,'idol::TempVar']]],
  ['set_5ftype_6',['set_type',['../classidol_1_1TempCtr.html#a864b1daa13c5671d4d1bd111c50de72b',1,'idol::TempCtr::set_type()'],['../classidol_1_1TempVar.html#a49488fba31d59ad3cdfeea5b578576c4',1,'idol::TempVar::set_type(VarType t_type)']]],
  ['set_5fub_7',['set_ub',['../classidol_1_1TempVar.html#a7bc8216524501353d1bfcdf151c89995',1,'idol::TempVar']]],
  ['side_20uncertainty_8',['Right-hand Side Uncertainty',['../cli_robust_basics.html#cli_robust_rhs_file',1,'']]],
  ['side_5feffect_5fregistry_9',['side_effect_registry',['../classidol_1_1BranchAndBoundCallback.html#a2dd664ba2acaffb86a06475b64ec1492',1,'idol::BranchAndBoundCallback']]],
  ['sideeffectregistry_10',['SideEffectRegistry',['../structidol_1_1SideEffectRegistry.html',1,'idol']]],
  ['silentmode_11',['SilentMode',['../classidol_1_1SilentMode.html',1,'idol']]],
  ['simple_20models_12',['Building and solving simple models',['../examples_mixed_integer.html#examples_mixed_integer_modeling',1,'']]],
  ['simplerounding_13',['SimpleRounding',['../classidol_1_1Heuristics_1_1SimpleRounding.html',1,'idol::Heuristics']]],
  ['single_20level_20reformulation_14',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['size_15',['Solution Pool Size',['../lib_milp_bnb_options.html#lib_milp_bnb_options_solution_pool',1,'']]],
  ['size_20model_16',['An Exponential-Size Model',['../example_mixed_integer_tsp_gurobi.html#autotoc_md7',1,'']]],
  ['solution_20pool_20size_17',['Solution Pool Size',['../lib_milp_bnb_options.html#lib_milp_bnb_options_solution_pool',1,'']]],
  ['solver_18',['Solver',['../cli_bilevel_kkt.html#kkt_other_milp_solver',1,'Changing the Underlying MILP Solver'],['../index.html#is_this_a_mip_solver',1,'Is this a MIP Solver?'],['../lib_milp_basics.html#lib_milp_basics_solving',1,'Using an External Solver']]],
  ['solver_19',['Cannot find Cplex, GLPK, Gurobi, HiGHS, or any other solver',['../cannot_find_solver.html',1,'']]],
  ['solving_20a_20pessimistic_20bilevel_20problem_20',['Solving A Pessimistic Bilevel Problem',['../cli_bilevel_basics.html#cli_bilevel_basics_pessimistic',1,'']]],
  ['solving_20a_20two_20stage_20robust_20problem_21',['Solving a Two-Stage Robust Problem',['../cli_robust_basics.html#cli_robust_basics_aro_solving',1,'']]],
  ['solving_20an_20optimistic_20bilevel_20problem_22',['Solving An Optimistic Bilevel Problem',['../cli_bilevel_basics.html#cli_bilevel_basics_optimistic',1,'']]],
  ['solving_20bilevel_20problems_20via_20its_20kkt_20based_20single_20level_20reformulation_23',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['solving_20simple_20models_24',['Building and solving simple models',['../examples_mixed_integer.html#examples_mixed_integer_modeling',1,'']]],
  ['solving_20your_20first_20milp_25',['Solving Your First MILP',['../cli_milp_basics.html#cli_milp_basics_first',1,'']]],
  ['sos1_20formulation_26',['Using the SOS1 Formulation',['../cli_bilevel_kkt.html#kkt_sos1',1,'']]],
  ['sos1_20gurobi_27',['sos1-gurobi',['../example_mixed_integer_sos1_gurobi.html',1,'examples_mixed_integer']]],
  ['sosctr_28',['SOSCtr',['../classidol_1_1SOSCtr.html',1,'idol']]],
  ['sosctrversion_29',['SOSCtrVersion',['../classidol_1_1SOSCtrVersion.html',1,'idol']]],
  ['source_30',['Source',['../cli_installation.html#from_source',1,'From Source'],['../lib_installation.html#lib_install_from_source',1,'From Source']]],
  ['source_31',['Build from source',['../build_from_source.html',1,'']]],
  ['sparsevector_32',['SparseVector',['../classidol_1_1SparseVector.html',1,'idol']]],
  ['sparsevector_3c_20commutativepair_3c_20idol_3a_3avar_20_3e_2c_20double_20_3e_33',['SparseVector&lt; CommutativePair&lt; idol::Var &gt;, double &gt;',['../classidol_1_1SparseVector.html',1,'idol']]],
  ['sparsevector_3c_20commutativepair_3c_20idol_3a_3avar_20_3e_2c_20idol_3a_3aquadexpr_3c_20idol_3a_3avar_20_3e_20_3e_34',['SparseVector&lt; CommutativePair&lt; idol::Var &gt;, idol::QuadExpr&lt; idol::Var &gt; &gt;',['../classidol_1_1SparseVector.html',1,'idol']]],
  ['sparsevector_3c_20idol_3a_3actr_2c_20double_20_3e_35',['SparseVector&lt; idol::Ctr, double &gt;',['../classidol_1_1SparseVector.html',1,'idol']]],
  ['sparsevector_3c_20idol_3a_3actr_2c_20idol_3a_3alinexpr_3c_20idol_3a_3avar_20_3e_20_3e_36',['SparseVector&lt; idol::Ctr, idol::LinExpr&lt; idol::Var &gt; &gt;',['../classidol_1_1SparseVector.html',1,'idol']]],
  ['sparsevector_3c_20idol_3a_3avar_2c_20double_20_3e_37',['SparseVector&lt; idol::Var, double &gt;',['../classidol_1_1SparseVector.html',1,'idol']]],
  ['sparsevector_3c_20idol_3a_3avar_2c_20idol_3a_3alinexpr_3c_20idol_3a_3avar_20_3e_20_3e_38',['SparseVector&lt; idol::Var, idol::LinExpr&lt; idol::Var &gt; &gt;',['../classidol_1_1SparseVector.html',1,'idol']]],
  ['sparsevector_3c_20idol_3a_3avar_2c_20idol_3a_3aquadexpr_3c_20idol_3a_3avar_20_3e_20_3e_39',['SparseVector&lt; idol::Var, idol::QuadExpr&lt; idol::Var &gt; &gt;',['../classidol_1_1SparseVector.html',1,'idol']]],
  ['sparsevector_3c_20keyt_2c_20idol_3a_3aaffexpr_3c_20idol_3a_3avar_20_3e_20_3e_40',['SparseVector&lt; KeyT, idol::AffExpr&lt; idol::Var &gt; &gt;',['../classidol_1_1SparseVector.html',1,'idol']]],
  ['sparsevector_3c_20t_2c_20double_20_3e_41',['SparseVector&lt; T, double &gt;',['../classidol_1_1SparseVector.html',1,'idol']]],
  ['sparsity_42',['Sparsity',['../namespaceidol_1_1Tolerance.html#af9089aedbd007a648ad7f6d032b64a77',1,'idol::Tolerance']]],
  ['specific_20callback_43',['Writing a Branch-and-Bound-Specific Callback',['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_specific',1,'']]],
  ['stabilizing_20column_20generation_20via_20in_20out_20separation_44',['Stabilizing Column Generation via in-out Separation',['../lib_milp_branch_and_price_cg_in_out.html',1,'lib_milp_branch_and_price']]],
  ['stables_20features_45',['Stables features',['../stable_features.html',1,'']]],
  ['stage_20robust_20optimization_46',['Two-Stage Robust Optimization',['../cli_robust_basics.html#cli_robust_basics_aro',1,'']]],
  ['stage_20robust_20problem_47',['Solving a Two-Stage Robust Problem',['../cli_robust_basics.html#cli_robust_basics_aro_solving',1,'']]],
  ['start_48',['Quick Start',['../index.html#quick_start',1,'']]],
  ['start_49',['start',['../classidol_1_1Timer.html#ad0a054b259477ddb2f8de6ea07616ce5',1,'idol::Timer']]],
  ['static_20robust_20optimization_50',['Static Robust Optimization',['../cli_robust_basics.html#cli_robust_basics_static',1,'']]],
  ['step_201_20—_20clone_20the_20repository_51',['Step 1 — Clone the repository',['../build_from_source.html#step_clone',1,'']]],
  ['step_202_20—_20create_20a_20build_20directory_52',['Step 2 — Create a build directory',['../build_from_source.html#step_build_dir',1,'']]],
  ['step_203_20—_20configure_20and_20build_53',['Step 3 — Configure and build',['../build_from_source.html#step_configure',1,'']]],
  ['step_204_20—_20install_54',['Step 4 — Install',['../build_from_source.html#step_install',1,'']]],
  ['step_205_20—_20verify_20installation_55',['Step 5 — Verify installation',['../build_from_source.html#step_verify',1,'']]],
  ['stop_56',['stop',['../classidol_1_1Timer.html#a194a67e24d9478af21d2b109385161ca',1,'idol::Timer']]],
  ['strategy_57',['Strategy',['../classidol_1_1BestBound_1_1Strategy.html',1,'idol::BestBound::Strategy&lt; NodeT &gt;'],['../classidol_1_1BestEstimate_1_1Strategy.html',1,'idol::BestEstimate::Strategy&lt; NodeT &gt;'],['../classidol_1_1BreadthFirst_1_1Strategy.html',1,'idol::BreadthFirst::Strategy&lt; NodeT &gt;'],['../classidol_1_1CallbackAsBranchAndBoundCallback_1_1Strategy.html',1,'idol::CallbackAsBranchAndBoundCallback&lt; NodeInfoT &gt;::Strategy'],['../classidol_1_1CglCutCallback_1_1Strategy.html',1,'idol::CglCutCallback&lt; NodeInfoT &gt;::Strategy'],['../classidol_1_1Cuts_1_1KnapsackCover_1_1Strategy.html',1,'idol::Cuts::KnapsackCover&lt; NodeInfoT &gt;::Strategy'],['../classidol_1_1DantzigWolfe_1_1ArtificialCosts_1_1Strategy.html',1,'idol::DantzigWolfe::ArtificialCosts::Strategy'],['../classidol_1_1DantzigWolfe_1_1DualPriceSmoothingStabilization_1_1Strategy.html',1,'idol::DantzigWolfe::DualPriceSmoothingStabilization::Strategy'],['../classidol_1_1DantzigWolfe_1_1FarkasPricing_1_1Strategy.html',1,'idol::DantzigWolfe::FarkasPricing::Strategy'],['../classidol_1_1DantzigWolfe_1_1InfeasibilityStrategyFactory_1_1Strategy.html',1,'idol::DantzigWolfe::InfeasibilityStrategyFactory::Strategy'],['../classidol_1_1DantzigWolfe_1_1Neame_1_1Strategy.html',1,'idol::DantzigWolfe::Neame::Strategy'],['../classidol_1_1DantzigWolfe_1_1NoStabilization_1_1Strategy.html',1,'idol::DantzigWolfe::NoStabilization::Strategy'],['../classidol_1_1DantzigWolfe_1_1Wentges_1_1Strategy.html',1,'idol::DantzigWolfe::Wentges::Strategy'],['../classidol_1_1DepthFirst_1_1Strategy.html',1,'idol::DepthFirst::Strategy&lt; NodeT &gt;'],['../classidol_1_1Diver_1_1Strategy.html',1,'idol::Diver&lt; BranchingRuleT &gt;::Strategy&lt; NodeInfoT &gt;'],['../classidol_1_1FirstInfeasibleFound_1_1Strategy.html',1,'idol::FirstInfeasibleFound::Strategy&lt; NodeInfoT &gt;'],['../classidol_1_1Heuristics_1_1IntegerMaster_1_1Strategy.html',1,'idol::Heuristics::IntegerMaster&lt; NodeInfoT &gt;::Strategy'],['../classidol_1_1Heuristics_1_1LocalBranching_1_1Strategy.html',1,'idol::Heuristics::LocalBranching::Strategy'],['../classidol_1_1Heuristics_1_1LocalMIP_1_1Strategy.html',1,'idol::Heuristics::LocalMIP&lt; NodeInfoT &gt;::Strategy'],['../classidol_1_1Heuristics_1_1RENS_1_1Strategy.html',1,'idol::Heuristics::RENS::Strategy'],['../classidol_1_1Heuristics_1_1SimpleRounding_1_1Strategy.html',1,'idol::Heuristics::SimpleRounding::Strategy'],['../classidol_1_1LazyCutCallback_1_1Strategy.html',1,'idol::LazyCutCallback::Strategy'],['../classidol_1_1LeastInfeasible_1_1Strategy.html',1,'idol::LeastInfeasible::Strategy&lt; NodeInfoT &gt;'],['../classidol_1_1Logs_1_1BranchAndBound_1_1Factory_1_1Strategy.html',1,'idol::Logs::BranchAndBound::Factory&lt; NodeInfoT &gt;::Strategy'],['../classidol_1_1Logs_1_1BranchAndBound_1_1Info_1_1Strategy.html',1,'idol::Logs::BranchAndBound::Info&lt; NodeInfoT &gt;::Strategy'],['../classidol_1_1Logs_1_1DantzigWolfe_1_1Factory_1_1Strategy.html',1,'idol::Logs::DantzigWolfe::Factory::Strategy'],['../classidol_1_1Logs_1_1DantzigWolfe_1_1Info_1_1Strategy.html',1,'idol::Logs::DantzigWolfe::Info::Strategy'],['../classidol_1_1MostInfeasible_1_1Strategy.html',1,'idol::MostInfeasible::Strategy&lt; NodeInfoT &gt;'],['../classidol_1_1Plots_1_1OptimalityGap_1_1Strategy.html',1,'idol::Plots::OptimalityGap::Strategy'],['../classidol_1_1PseudoCost_1_1Strategy.html',1,'idol::PseudoCost::Strategy&lt; NodeInfoT &gt;'],['../classidol_1_1ReducedCostFixing_1_1Strategy.html',1,'idol::ReducedCostFixing&lt; NodeInfoT &gt;::Strategy'],['../classidol_1_1StrongBranching_1_1Strategy.html',1,'idol::StrongBranching::Strategy&lt; NodeInfoT &gt;'],['../classidol_1_1UniformlyRandom_1_1Strategy.html',1,'idol::UniformlyRandom::Strategy&lt; NodeInfoT &gt;'],['../classidol_1_1UserCutCallback_1_1Strategy.html',1,'idol::UserCutCallback::Strategy'],['../classidol_1_1Utils_1_1ExportBranchAndBoundTreeToCSV_1_1Strategy.html',1,'idol::Utils::ExportBranchAndBoundTreeToCSV&lt; NodeInfoT &gt;::Strategy'],['../classidol_1_1VariableBranching_1_1Strategy.html',1,'idol::VariableBranching::Strategy&lt; NodeT &gt;'],['../classidol_1_1WorstBound_1_1Strategy.html',1,'idol::WorstBound::Strategy&lt; NodeT &gt;']]],
  ['strategy_3c_20nodeinfot_20_3e_58',['Strategy&lt; NodeInfoT &gt;',['../classidol_1_1VariableBranching_1_1Strategy.html',1,'idol::VariableBranching']]],
  ['strengthening_59',['One Row Bound Strengthening',['../lib_milp_bnb_presolve.html#lib_milp_bnb_presolve_OneRowBoundStrengthening',1,'']]],
  ['strong_20branching_60',['Strong Branching',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_full',1,'Full Strong Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_restricted',1,'Restricted Strong Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching',1,'Strong Branching']]],
  ['strong_20branching_20with_20look_20ahead_61',['Strong Branching with Look Ahead',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_look_ahead',1,'']]],
  ['strong_20branching_20with_20phases_62',['Strong Branching with Phases',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_phases',1,'']]],
  ['strongbranching_63',['StrongBranching',['../classidol_1_1BranchingRules_1_1StrongBranching.html',1,'idol::BranchingRules::StrongBranching&lt; NodeInfoT &gt;'],['../classidol_1_1StrongBranching.html',1,'idol::StrongBranching']]],
  ['strongbranchingphase_64',['StrongBranchingPhase',['../classidol_1_1StrongBranchingPhase.html',1,'idol']]],
  ['strongbranchingphasetype_65',['StrongBranchingPhaseType',['../classidol_1_1StrongBranchingPhaseType.html',1,'idol']]],
  ['strongduality_66',['StrongDuality',['../classidol_1_1Bilevel_1_1StrongDuality.html',1,'idol::Bilevel::StrongDuality'],['../classidol_1_1Optimizers_1_1Bilevel_1_1StrongDuality.html',1,'idol::Optimizers::Bilevel::StrongDuality']]],
  ['sub_20tour_20elimination_20constraints_67',['Sub-Tour Elimination Constraints',['../example_mixed_integer_tsp_gurobi.html#autotoc_md11',1,'']]],
  ['sub_20trees_68',['Sub-Trees',['../lib_milp_bnb_options.html#lib_milp_bnb_options_sub_tree',1,'']]],
  ['submit_5fbound_69',['submit_bound',['../classidol_1_1BranchAndBoundCallback.html#ae81dfc23113d406f7be2e4ecba59b0e4',1,'idol::BranchAndBoundCallback']]],
  ['submit_5fheuristic_5fsolution_70',['submit_heuristic_solution',['../classidol_1_1BranchAndBoundCallback.html#a20f80c0b74e78b6bc7ee8cc8ef8c174d',1,'idol::BranchAndBoundCallback::submit_heuristic_solution()'],['../classidol_1_1Callback.html#aba8b5815a8701fadc611bea822bca68b',1,'idol::Callback::submit_heuristic_solution()']]],
  ['subproblem_71',['SubProblem',['../structidol_1_1ADM_1_1Formulation_1_1SubProblem.html',1,'idol::ADM::Formulation::SubProblem'],['../classidol_1_1ADM_1_1SubProblem.html',1,'idol::ADM::SubProblem'],['../classidol_1_1DantzigWolfe_1_1SubProblem.html',1,'idol::DantzigWolfe::SubProblem']]],
  ['sudoku_20cplex_72',['sudoku-cplex',['../example_mixed_integer_sudoku_cplex.html',1,'examples_mixed_integer']]],
  ['support_73',['support',['../build_from_source.html#cmake_cgl',1,'Enable Cgl support'],['../build_from_source.html#cmake_mibs',1,'Enable MibS support']]]
];
