var searchData=
[
  ['m_20reformulation_0',['Using the Big-M Reformulation',['../cli_bilevel_kkt.html#kkt_big_m',1,'']]],
  ['macos_20arm64_1',['MacOs arm64',['../cli_installation.html#mac',1,'MacOs (arm64)'],['../lib_installation.html#lib_install_mac',1,'MacOs (arm64)']]],
  ['make_5fvector_2',['make_vector',['../classidol_1_1Ctr.html#adff189bf532775589a819d4e6a94ff32',1,'idol::Ctr::make_vector()'],['../classidol_1_1Var.html#aeb0693f77f998802e3b944a33b6b9c58',1,'idol::Var::make_vector()']]],
  ['making_20the_20master_20problem_20feasible_20phase_20i_3',['Making the Master Problem Feasible (Phase I)',['../lib_milp_branch_and_price_cg_phaseI.html',1,'lib_milp_branch_and_price']]],
  ['manager_4',['Manager',['../classidol_1_1Plots_1_1Manager.html',1,'idol::Plots']]],
  ['master_20heuristic_5',['The &quot;Integer Master&quot; Heuristic',['../lib_milp_branch_and_price_bap_IntegerMaster.html',1,'lib_milp_branch_and_price']]],
  ['master_20problem_20feasible_20phase_20i_6',['Making the Master Problem Feasible (Phase I)',['../lib_milp_branch_and_price_cg_phaseI.html',1,'lib_milp_branch_and_price']]],
  ['matrix_20uncertainty_7',['Constraint Matrix Uncertainty',['../cli_robust_basics.html#cli_robust_mat_file',1,'']]],
  ['mibs_8',['MibS',['../classidol_1_1Bilevel_1_1MibS.html',1,'idol::Bilevel::MibS'],['../classidol_1_1Optimizers_1_1Bilevel_1_1MibS.html',1,'idol::Optimizers::Bilevel::MibS']]],
  ['mibs_9',['moore-bard-mibs',['../example_bilevel_moore_bard_mibs.html',1,'examples_bilevel']]],
  ['mibs_20support_10',['Enable MibS support',['../build_from_source.html#cmake_mibs',1,'']]],
  ['milp_11',['Solving Your First MILP',['../cli_milp_basics.html#cli_milp_basics_first',1,'']]],
  ['milp_20solver_12',['Changing the Underlying MILP Solver',['../cli_bilevel_kkt.html#kkt_other_milp_solver',1,'']]],
  ['milps_13',['Basics of the Command Line Interface for MILPs',['../cli_milp_basics.html',1,'']]],
  ['mip_20solver_14',['Is this a MIP Solver?',['../index.html#is_this_a_mip_solver',1,'']]],
  ['mixed_20integer_20bilevel_20optimization_15',['Mixed-integer bilevel optimization',['../examples_bilevel.html#examples_bilevel_mixed_integer',1,'']]],
  ['mixed_20integer_20optimization_16',['Mixed-Integer Optimization',['../cli_tutorials.html#cli_tutorials_milp',1,'']]],
  ['mixed_20integer_20optimization_17',['Mixed integer optimization',['../examples_mixed_integer.html',1,'Mixed-integer optimization'],['../stable_features_mixed_integer.html',1,'Mixed-integer optimization']]],
  ['model_18',['Model',['../example_mixed_integer_tsp_gurobi.html#autotoc_md7',1,'An Exponential-Size Model'],['../classidol_1_1Model.html',1,'idol::Model'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md13',1,'The Full Model'],['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_create_model',1,'Using the Model']]],
  ['model_20and_20what_20can_20you_20do_20with_20it_19',['What is a Model and What Can You Do with It?',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_what',1,'']]],
  ['models_20',['Models',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_copy',1,'Copying and Moving Models'],['../lib_milp_basics_advanced_models.html',1,'Models']]],
  ['models_21',['Building and solving simple models',['../examples_mixed_integer.html#examples_mixed_integer_modeling',1,'']]],
  ['modifying_20variables_22',['Modifying Variables',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_modify',1,'']]],
  ['moore_20bard_20mibs_23',['moore-bard-mibs',['../example_bilevel_moore_bard_mibs.html',1,'examples_bilevel']]],
  ['more_20advanced_20features_24',['More advanced features',['../examples_mixed_integer.html#examples_mixed_integer_mored_advanced_features',1,'']]],
  ['more_20advanced_20topics_25',['More Advanced Topics',['../lib_milp_basics.html#lib_milp_basics_advanced',1,'More Advanced Topics'],['../lib_milp_branch_and_bound.html#lib_milp_bnb_sub_pages',1,'More Advanced Topics'],['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced',1,'More Advanced Topics']]],
  ['most_20infeasible_26',['Most Infeasible',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_MostInfeasible',1,'']]],
  ['mostinfeasible_27',['MostInfeasible',['../classidol_1_1BranchingRules_1_1MostInfeasible.html',1,'idol::BranchingRules::MostInfeasible&lt; NodeInfoT &gt;'],['../classidol_1_1MostInfeasible.html',1,'idol::MostInfeasible']]],
  ['moving_20models_28',['Copying and Moving Models',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_copy',1,'']]],
  ['mps_29',['Example (.lp and .mps)',['../cli_milp_basics.html#cli_milp_example_lp',1,'']]],
  ['multiple_20variables_20at_20once_30',['Creating Multiple Variables at Once',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_create_array',1,'']]],
  ['multiplicative_31',['Multiplicative',['../classidol_1_1PenaltyUpdates_1_1Multiplicative.html',1,'idol::PenaltyUpdates']]],
  ['multiplicities_32',['Multiplicities',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_multiplicities',1,'']]],
  ['mutablecoefficient_33',['MutableCoefficient',['../structidol_1_1Problems_1_1Counterfactual_1_1Instance_1_1MutableCoefficient.html',1,'idol::Problems::Counterfactual::Instance']]],
  ['mutablecost_34',['MutableCost',['../structidol_1_1Problems_1_1Counterfactual_1_1Instance_1_1MutableCost.html',1,'idol::Problems::Counterfactual::Instance']]],
  ['mutablerhs_35',['MutableRhs',['../structidol_1_1Problems_1_1Counterfactual_1_1Instance_1_1MutableRhs.html',1,'idol::Problems::Counterfactual::Instance']]]
];
