var searchData=
[
  ['i_0',['Making the Master Problem Feasible (Phase I)',['../lib_milp_branch_and_price_cg_phaseI.html',1,'lib_milp_branch_and_price']]],
  ['id_1',['id',['../classidol_1_1Object.html#ac8e398b9b937f08b1c5dbd2b32414036',1,'idol::Object::id()'],['../classidol_1_1Param.html#a41243b2248da219ea1467bb0898e025a',1,'idol::Param::id()']]],
  ['identity_2',['identity',['../structidol_1_1identity.html',1,'idol']]],
  ['idol_3',['idol',['../example_mixed_integer_bin_bap.html#autotoc_md2',1,'Implementation in idol'],['../example_mixed_integer_gap_bap.html#autotoc_md6',1,'Implementation in idol'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md14',1,'Implementation in idol']]],
  ['idol_20c_20library_4',['The &lt;span class=&quot;tt&quot;&gt;idol&lt;/span&gt; C++ Library',['../index.html#getting_started_with_idol',1,'']]],
  ['idol_20using_20cmake_5',['Linking with &lt;span class=&quot;tt&quot;&gt;idol&lt;/span&gt; using CMake',['../lib_installation.html#lib_linking',1,'']]],
  ['idol_3a_3atolerance_6',['Tolerance',['../namespaceidol_1_1Tolerance.html',1,'idol']]],
  ['implementation_20in_20idol_7',['Implementation in idol',['../example_mixed_integer_bin_bap.html#autotoc_md2',1,'Implementation in idol'],['../example_mixed_integer_gap_bap.html#autotoc_md6',1,'Implementation in idol'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md14',1,'Implementation in idol']]],
  ['in_20idol_8',['in idol',['../example_mixed_integer_bin_bap.html#autotoc_md2',1,'Implementation in idol'],['../example_mixed_integer_gap_bap.html#autotoc_md6',1,'Implementation in idol'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md14',1,'Implementation in idol']]],
  ['in_20out_20separation_9',['Stabilizing Column Generation via in-out Separation',['../lib_milp_branch_and_price_cg_in_out.html',1,'lib_milp_branch_and_price']]],
  ['inequalities_10',['Deactivating Kleinart et al. (2020) Valid Inequalities',['../cli_bilevel_kkt.html#kkt_kleinert_vi',1,'']]],
  ['infeasibilitystrategyfactory_11',['InfeasibilityStrategyFactory',['../classidol_1_1DantzigWolfe_1_1InfeasibilityStrategyFactory.html',1,'idol::DantzigWolfe']]],
  ['infeasible_12',['Infeasible',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_LeastInfeasible',1,'Least Infeasible'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_MostInfeasible',1,'Most Infeasible']]],
  ['infeasible_20found_13',['First Infeasible Found',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_FirstInfeasibleFound',1,'']]],
  ['info_14',['Info',['../classidol_1_1Logs_1_1BranchAndBound_1_1Info.html',1,'idol::Logs::BranchAndBound::Info&lt; NodeInfoT &gt;'],['../classidol_1_1Logs_1_1DantzigWolfe_1_1Info.html',1,'idol::Logs::DantzigWolfe::Info']]],
  ['initialize_15',['initialize',['../classidol_1_1BranchAndBoundCallback.html#acfa261050e03bf300457218a38be51d6',1,'idol::BranchAndBoundCallback::initialize()'],['../classidol_1_1CglCutCallback_1_1Strategy.html#ae1505e15f5853ef4bbb1f23d859476b0',1,'idol::CglCutCallback::Strategy::initialize()'],['../classidol_1_1Cuts_1_1KnapsackCover_1_1Strategy.html#ac3b637513554dd08621768a8dfd79dff',1,'idol::Cuts::KnapsackCover::Strategy::initialize()']]],
  ['input_20file_20format_16',['Input File Format',['../cli_bilevel_basics.html#cli_bilevel_basics_input',1,'Input File Format'],['../cli_milp_basics.html#cli_milp_basics_input',1,'Input File Format'],['../cli_robust_basics.html#cli_robust_basics_input',1,'Input File Format'],['../cli_robust_basics.html#cli_robust_basics_aro_input',1,'Input File Format']]],
  ['install_17',['Step 4 — Install',['../build_from_source.html#step_install',1,'']]],
  ['installation_18',['Installation',['../cli_installation.html',1,'Installation'],['../lib_installation.html',1,'Installation'],['../lib_installation.html#lib_install',1,'Installation']]],
  ['installation_19',['Step 5 — Verify installation',['../build_from_source.html#step_verify',1,'']]],
  ['installation_20directory_20',['Custom installation directory',['../build_from_source.html#cmake_install_prefix',1,'']]],
  ['installation_20guidelines_21',['Installation guidelines',['../installation.html',1,'']]],
  ['instance_22',['Instance',['../classidol_1_1Problems_1_1Counterfactual_1_1Instance.html',1,'idol::Problems::Counterfactual::Instance'],['../classidol_1_1Problems_1_1FLP_1_1Instance.html',1,'idol::Problems::FLP::Instance'],['../classidol_1_1Problems_1_1GAP_1_1Instance.html',1,'idol::Problems::GAP::Instance'],['../classidol_1_1Problems_1_1KP_1_1Instance.html',1,'idol::Problems::KP::Instance'],['../classidol_1_1Problems_1_1MKP_1_1Instance.html',1,'idol::Problems::MKP::Instance'],['../classidol_1_1Problems_1_1SRP_1_1Instance.html',1,'idol::Problems::SRP::Instance']]],
  ['instances_23',['Instances',['../cli_instances.html',1,'']]],
  ['instructions_24',['Build instructions',['../build_from_source.html#build_steps',1,'']]],
  ['integer_20bilevel_20optimization_25',['Mixed-integer bilevel optimization',['../examples_bilevel.html#examples_bilevel_mixed_integer',1,'']]],
  ['integer_20master_20heuristic_26',['The &quot;Integer Master&quot; Heuristic',['../lib_milp_branch_and_price_bap_IntegerMaster.html',1,'lib_milp_branch_and_price']]],
  ['integer_20optimization_27',['Mixed-Integer Optimization',['../cli_tutorials.html#cli_tutorials_milp',1,'']]],
  ['integer_20optimization_28',['integer optimization',['../examples_mixed_integer.html',1,'Mixed-integer optimization'],['../stable_features_mixed_integer.html',1,'Mixed-integer optimization']]],
  ['integermaster_29',['IntegerMaster',['../classidol_1_1Heuristics_1_1IntegerMaster.html',1,'idol::Heuristics']]],
  ['integrality_20constraints_30',['Integrality Constraints',['../example_mixed_integer_tsp_gurobi.html#autotoc_md12',1,'']]],
  ['interface_31',['Tutorials for the Command Line Interface',['../cli_tutorials.html',1,'']]],
  ['interface_20for_20bilevel_20optimization_32',['Basics of the Command Line Interface for Bilevel Optimization',['../cli_bilevel_basics.html',1,'']]],
  ['interface_20for_20milps_33',['Basics of the Command Line Interface for MILPs',['../cli_milp_basics.html',1,'']]],
  ['interface_20for_20robust_20problems_34',['Basics of the Command Line Interface for Robust Problems',['../cli_robust_basics.html',1,'']]],
  ['introduction_35',['Introduction',['../cli_bilevel_kkt.html#kkt_introduction',1,'Introduction'],['../cli_robust_basics.html#cli_robust_basics_intro',1,'Introduction'],['../cli_robust_basics.html#cli_robust_basics_aro_introduction',1,'Introduction']]],
  ['is_36',['is',['../classidol_1_1Param.html#a3a60236e5a635f6611c172b74777d93a',1,'idol::Param']]],
  ['is_20a_20model_20and_20what_20can_20you_20do_20with_20it_37',['What is a Model and What Can You Do with It?',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_what',1,'']]],
  ['is_20an_20optimization_20environment_38',['What is an Optimization Environment',['../lib_milp_basics_advanced_environment.html#lib_milp_basics_advanced_environment_what',1,'']]],
  ['is_20this_20a_20mip_20solver_39',['Is this a MIP Solver?',['../index.html#is_this_a_mip_solver',1,'']]],
  ['is_5fin_40',['is_in',['../classidol_1_1Object.html#aa25899704860cb066f885015ec1f11f3',1,'idol::Object']]],
  ['it_41',['What is a Model and What Can You Do with It?',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_what',1,'']]],
  ['item_42',['Item',['../structidol_1_1Cuts_1_1KnapsackCover_1_1Strategy_1_1KnapsackStructure_1_1Item.html',1,'idol::Cuts::KnapsackCover::Strategy::KnapsackStructure']]],
  ['iterationplot_43',['IterationPlot',['../classidol_1_1Optimizers_1_1PADM_1_1IterationPlot.html',1,'idol::Optimizers::PADM']]],
  ['iterator_44',['iterator',['../classidol_1_1Range_1_1iterator.html',1,'idol::Range']]],
  ['iteratorforward_45',['IteratorForward',['../classidol_1_1IteratorForward.html',1,'idol']]],
  ['iteratorforward_3c_20std_3a_3alist_3c_20std_3a_3apair_3c_20keyt_2c_20valuet_20_3e_20_3e_20_3e_46',['IteratorForward&lt; std::list&lt; std::pair&lt; KeyT, ValueT &gt; &gt; &gt;',['../classidol_1_1IteratorForward.html',1,'idol']]],
  ['its_20kkt_20based_20single_20level_20reformulation_47',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]]
];
