var searchData=
[
  ['bab_0',['flp-bab',['../example_mixed_integer_flp_bab.html',1,'examples_mixed_integer']]],
  ['bap_1',['bap',['../example_mixed_integer_bin_bap.html',1,'bin-bap'],['../example_mixed_integer_gap_bap.html',1,'gap-bap']]],
  ['bard_20mibs_2',['moore-bard-mibs',['../example_bilevel_moore_bard_mibs.html',1,'examples_bilevel']]],
  ['based_20single_20level_20reformulation_3',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['basics_4',['Basics',['../cli_basics.html',1,'']]],
  ['best_5fbound_5',['best_bound',['../classidol_1_1Callback.html#aec34a610d1edb398e806774b2ead856e',1,'idol::Callback']]],
  ['best_5fobj_6',['best_obj',['../classidol_1_1Callback.html#ab45dfb3e9f7155de67fceb474a0dd827',1,'idol::Callback']]],
  ['bestbound_7',['BestBound',['../classidol_1_1BestBound.html',1,'idol::BestBound'],['../classidol_1_1NodeSelectionRules_1_1BestBound.html',1,'idol::NodeSelectionRules::BestBound&lt; NodeT &gt;']]],
  ['bestestimate_8',['BestEstimate',['../classidol_1_1BestEstimate.html',1,'idol::BestEstimate'],['../classidol_1_1NodeSelectionRules_1_1BestEstimate.html',1,'idol::NodeSelectionRules::BestEstimate&lt; NodeT &gt;']]],
  ['big_20m_20reformulation_9',['Using the Big-M Reformulation',['../cli_bilevel_kkt.html#kkt_big_m',1,'']]],
  ['bigmfreeseparation_10',['BigMFreeSeparation',['../classidol_1_1Robust_1_1CCG_1_1BigMFreeSeparation.html',1,'idol::Robust::CCG']]],
  ['bilevel_20optimization_11',['Bilevel optimization',['../examples_bilevel.html',1,'Bilevel optimization'],['../stable_features_bilevel.html',1,'Bilevel optimization']]],
  ['bilevel_20optimization_12',['bilevel optimization',['../examples_bilevel.html#examples_bilevel_continuous',1,'Continuous bilevel optimization'],['../examples_bilevel.html#examples_bilevel_mixed_integer',1,'Mixed-integer bilevel optimization'],['../examples_bilevel.html#examples_bilevel_mixed_integer_pessimistic',1,'Pessimistic bilevel optimization']]],
  ['bilevel_20problems_13',['Bilevel Problems',['../cli_basics.html#cli_basics_bilevel',1,'Bilevel Problems'],['../cli_input_format_bilevel.html',1,'Input Format for Bilevel Problems']]],
  ['bilevel_20problems_20via_20its_20kkt_20based_20single_20level_20reformulation_14',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['bilevelbasedbranchandbound_15',['BilevelBasedBranchAndBound',['../classidol_1_1Optimizers_1_1Robust_1_1BilevelBasedBranchAndBound.html',1,'idol::Optimizers::Robust::BilevelBasedBranchAndBound'],['../classidol_1_1Robust_1_1BilevelBasedBranchAndBound.html',1,'idol::Robust::BilevelBasedBranchAndBound']]],
  ['bin_20bap_16',['bin-bap',['../example_mixed_integer_bin_bap.html',1,'examples_mixed_integer']]],
  ['bound_20algorithm_17',['Branch-and-bound algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'']]],
  ['boundprovider_18',['BoundProvider',['../classidol_1_1Reformulators_1_1KKT_1_1BoundProvider.html',1,'idol::Reformulators::KKT::BoundProvider'],['../classidol_1_1Robust_1_1CCG_1_1BigMFreeSeparation_1_1BoundProvider.html',1,'idol::Robust::CCG::BigMFreeSeparation::BoundProvider']]],
  ['boundprovidermap_19',['BoundProviderMap',['../classidol_1_1Reformulators_1_1KKT_1_1BoundProviderMap.html',1,'idol::Reformulators::KKT']]],
  ['bounds_20',['Reference for Dual Variable Bounds',['../cli_bilevel_kkt.html#kkt_big_m_def',1,'']]],
  ['bounds_20on_20the_20dual_20variables_21',['The File Format for Providing Bounds on the Dual Variables',['../cli_bilevel_kkt.html#kkt_big_m_file',1,'']]],
  ['branch_20and_20bound_20algorithm_22',['Branch-and-bound algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'']]],
  ['branch_20and_20price_20algorithm_23',['Branch-and-price algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'']]],
  ['branchandbound_24',['BranchAndBound',['../classidol_1_1BranchAndBound.html',1,'idol::BranchAndBound&lt; NodeT &gt;'],['../classidol_1_1Optimizers_1_1BranchAndBound.html',1,'idol::Optimizers::BranchAndBound&lt; NodeInfoT &gt;'],['../classidol_1_1BranchAndBound.html#a96fec5e9e6f278c51ec788b317321616',1,'idol::BranchAndBound::BranchAndBound()=default'],['../classidol_1_1BranchAndBound.html#a15e010f0ecbb6ddde4ec3fee723564f0',1,'idol::BranchAndBound::BranchAndBound(const BranchAndBound &amp;t_rhs)']]],
  ['branchandbound_3c_20nodet_20_3e_25',['BranchAndBound&lt; NodeT &gt;',['../classidol_1_1Optimizers_1_1BranchAndBound.html',1,'idol::Optimizers']]],
  ['branchandboundcallback_26',['BranchAndBoundCallback',['../classidol_1_1BranchAndBoundCallback.html',1,'idol']]],
  ['branchandboundcallbackfactory_27',['BranchAndBoundCallbackFactory',['../classidol_1_1BranchAndBoundCallbackFactory.html',1,'idol']]],
  ['branchandboundcallbackfactory_3c_20idol_3a_3adefaultnodeinfo_20_3e_28',['BranchAndBoundCallbackFactory&lt; idol::DefaultNodeInfo &gt;',['../classidol_1_1BranchAndBoundCallbackFactory.html',1,'idol']]],
  ['branchandboundcallbacki_29',['BranchAndBoundCallbackI',['../classidol_1_1BranchAndBoundCallbackI.html',1,'idol']]],
  ['branchandcut_30',['BranchAndCut',['../classidol_1_1Bilevel_1_1BranchAndCut.html',1,'idol::Bilevel::BranchAndCut'],['../classidol_1_1Optimizers_1_1Bilevel_1_1BranchAndCut.html',1,'idol::Optimizers::Bilevel::BranchAndCut']]],
  ['branchingrule_31',['BranchingRule',['../classidol_1_1BranchingRule.html',1,'idol']]],
  ['branchingrulefactory_32',['BranchingRuleFactory',['../classidol_1_1BranchingRuleFactory.html',1,'idol']]],
  ['branchingrulefactory_3c_20idol_3a_3adefaultnodeinfo_20_3e_33',['BranchingRuleFactory&lt; idol::DefaultNodeInfo &gt;',['../classidol_1_1BranchingRuleFactory.html',1,'idol']]],
  ['branchingrulefactory_3c_20nodeinfot_20_3e_34',['BranchingRuleFactory&lt; NodeInfoT &gt;',['../classidol_1_1BranchingRuleFactory.html',1,'idol']]],
  ['branchingwithpriority_35',['BranchingWithPriority',['../classidol_1_1BranchingRules_1_1BranchingWithPriority.html',1,'idol::BranchingRules::BranchingWithPriority&lt; NodeInfoT &gt;'],['../classidol_1_1BranchingWithPriority.html',1,'idol::BranchingWithPriority&lt; NodeT &gt;']]],
  ['breadthfirst_36',['BreadthFirst',['../classidol_1_1BreadthFirst.html',1,'idol::BreadthFirst'],['../classidol_1_1NodeSelectionRules_1_1BreadthFirst.html',1,'idol::NodeSelectionRules::BreadthFirst&lt; NodeT &gt;']]],
  ['build_37',['Step 3 — Configure and build',['../build_from_source.html#step_configure',1,'']]],
  ['build_20directory_38',['Step 2 — Create a build directory',['../build_from_source.html#step_build_dir',1,'']]],
  ['build_20examples_39',['Build examples',['../build_from_source.html#cmake_examples',1,'']]],
  ['build_20from_20source_40',['Build from source',['../build_from_source.html',1,'']]],
  ['build_20instructions_41',['Build instructions',['../build_from_source.html#build_steps',1,'']]],
  ['build_20tests_42',['Build tests',['../build_from_source.html#cmake_tests',1,'']]],
  ['building_20and_20solving_20simple_20models_43',['Building and solving simple models',['../examples_mixed_integer.html#examples_mixed_integer_modeling',1,'']]]
];
