var searchData=
[
  ['padm_0',['PADM',['../classidol_1_1Optimizers_1_1PADM.html',1,'idol::Optimizers::PADM'],['../classidol_1_1PADM.html',1,'idol::PADM']]],
  ['pair_1',['Pair',['../structidol_1_1Pair.html',1,'idol']]],
  ['pair_3c_20t_2c_20t_20_3e_2',['Pair&lt; T, T &gt;',['../structidol_1_1Pair.html',1,'idol']]],
  ['param_3',['Param',['../classidol_1_1Param.html',1,'idol::Param'],['../classidol_1_1Param.html#abddc89cb7892eb4841efd6c219f8cfc1',1,'idol::Param::Param(const Var &amp;t_var)'],['../classidol_1_1Param.html#abd6102b12d3fccbf8ea7bdda12beda97',1,'idol::Param::Param(const Ctr &amp;t_ctr)'],['../classidol_1_1Param.html#aeaf61eb9ea6b75a37e0ff1554e24358b',1,'idol::Param::Param(const Param &amp;t_param)=default'],['../classidol_1_1Param.html#a7928ae7e1cd355ab0b3c5ef5442c8d68',1,'idol::Param::Param(Param &amp;&amp;t_param) noexcept=default']]],
  ['party_20tools_4',['Third Party Tools',['../about.html#autotoc_md16',1,'']]],
  ['penaltymethod_5',['PenaltyMethod',['../classidol_1_1PenaltyMethod.html',1,'idol']]],
  ['penaltyupdate_6',['PenaltyUpdate',['../classidol_1_1PenaltyUpdate.html',1,'idol']]],
  ['pess_7',['zeng-pess',['../example_bilevel_zeng_pess.html',1,'examples_bilevel']]],
  ['pessimistic_20bilevel_20optimization_8',['Pessimistic bilevel optimization',['../examples_bilevel.html#examples_bilevel_mixed_integer_pessimistic',1,'']]],
  ['pessimisticasoptimistic_9',['PessimisticAsOptimistic',['../classidol_1_1Bilevel_1_1PessimisticAsOptimistic.html',1,'idol::Bilevel::PessimisticAsOptimistic'],['../classidol_1_1Optimizers_1_1Bilevel_1_1PessimisticAsOptimistic.html',1,'idol::Optimizers::Bilevel::PessimisticAsOptimistic']]],
  ['point_10',['Point',['../classidol_1_1Point.html',1,'idol']]],
  ['point_3c_20ctr_20_3e_11',['Point&lt; Ctr &gt;',['../classidol_1_1Point.html',1,'idol']]],
  ['point_3c_20var_20_3e_12',['Point&lt; Var &gt;',['../classidol_1_1Point.html',1,'idol']]],
  ['price_20algorithm_13',['Branch-and-price algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'']]],
  ['pricing_20problem_14',['Deriving the Pricing Problem',['../example_mixed_integer_gap_bap.html#autotoc_md5',1,'']]],
  ['primal_5fsolution_15',['primal_solution',['../classidol_1_1Callback.html#ac1a19a08051cc57531e9c14422a026c0',1,'idol::Callback']]],
  ['problem_16',['Deriving the Pricing Problem',['../example_mixed_integer_gap_bap.html#autotoc_md5',1,'']]],
  ['problems_17',['Problems',['../cli_basics.html#cli_basics_bilevel',1,'Bilevel Problems'],['../cli_input_format_bilevel.html',1,'Input Format for Bilevel Problems'],['../cli_input_format_robust.html',1,'Input Format for Robust Problems'],['../cli_basics.html#cli_basics_aro',1,'Two-Stage Robust Problems']]],
  ['problems_20via_20its_20kkt_20based_20single_20level_20reformulation_18',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['product_19',['Product',['../classidol_1_1NodeScoreFunctions_1_1Product.html',1,'idol::NodeScoreFunctions']]],
  ['providing_20bounds_20on_20the_20dual_20variables_20',['The File Format for Providing Bounds on the Dual Variables',['../cli_bilevel_kkt.html#kkt_big_m_file',1,'']]],
  ['pseudocost_21',['PseudoCost',['../classidol_1_1BranchingRules_1_1PseudoCost.html',1,'idol::BranchingRules::PseudoCost&lt; NodeInfoT &gt;'],['../classidol_1_1PseudoCost.html',1,'idol::PseudoCost']]]
];
