var searchData=
[
  ['bab_0',['flp-bab',['../example_mixed_integer_flp_bab.html',1,'examples_mixed_integer']]],
  ['bap_1',['bap',['../example_mixed_integer_bin_bap.html',1,'bin-bap'],['../example_mixed_integer_gap_bap.html',1,'gap-bap']]],
  ['bard_20mibs_2',['moore-bard-mibs',['../example_bilevel_moore_bard_mibs.html',1,'examples_bilevel']]],
  ['best_5fbound_3',['best_bound',['../classidol_1_1Callback.html#aec34a610d1edb398e806774b2ead856e',1,'idol::Callback']]],
  ['best_5fobj_4',['best_obj',['../classidol_1_1Callback.html#ab45dfb3e9f7155de67fceb474a0dd827',1,'idol::Callback']]],
  ['bestbound_5',['bestbound',['../classidol_1_1NodeSelectionRules_1_1BestBound.html',1,'idol::NodeSelectionRules::BestBound&lt; NodeT &gt;'],['../classidol_1_1BestBound.html',1,'idol::BestBound']]],
  ['bestestimate_6',['bestestimate',['../classidol_1_1BestEstimate.html',1,'idol::BestEstimate'],['../classidol_1_1NodeSelectionRules_1_1BestEstimate.html',1,'idol::NodeSelectionRules::BestEstimate&lt; NodeT &gt;']]],
  ['bigmfreeseparation_7',['BigMFreeSeparation',['../classidol_1_1Robust_1_1CCG_1_1BigMFreeSeparation.html',1,'idol::Robust::CCG']]],
  ['bilevel_20optimization_8',['bilevel optimization',['../examples_bilevel.html',1,'Bilevel optimization'],['../stable_features_bilevel.html',1,'Bilevel optimization'],['../examples_bilevel.html#examples_bilevel_continuous',1,'Continuous bilevel optimization'],['../examples_bilevel.html#examples_bilevel_mixed_integer',1,'Mixed-integer bilevel optimization'],['../examples_bilevel.html#examples_bilevel_mixed_integer_pessimistic',1,'Pessimistic bilevel optimization']]],
  ['bilevelbasedbranchandbound_9',['bilevelbasedbranchandbound',['../classidol_1_1Robust_1_1BilevelBasedBranchAndBound.html',1,'idol::Robust::BilevelBasedBranchAndBound'],['../classidol_1_1Optimizers_1_1Robust_1_1BilevelBasedBranchAndBound.html',1,'idol::Optimizers::Robust::BilevelBasedBranchAndBound']]],
  ['bin_20bap_10',['bin-bap',['../example_mixed_integer_bin_bap.html',1,'examples_mixed_integer']]],
  ['boolean_20options_11',['boolean options',['../cmake-options.html#autotoc_md4',1,'Boolean Options'],['../cmake-options.html#autotoc_md1',1,'Boolean Options']]],
  ['bound_20algorithm_12',['Branch-and-bound algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'']]],
  ['boundprovider_13',['boundprovider',['../classidol_1_1Reformulators_1_1KKT_1_1BoundProvider.html',1,'idol::Reformulators::KKT::BoundProvider'],['../classidol_1_1Robust_1_1CCG_1_1BigMFreeSeparation_1_1BoundProvider.html',1,'idol::Robust::CCG::BigMFreeSeparation::BoundProvider']]],
  ['branch_20and_20bound_20algorithm_14',['Branch-and-bound algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'']]],
  ['branch_20and_20price_20algorithm_15',['Branch-and-price algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'']]],
  ['branchandbound_16',['branchandbound',['../classidol_1_1BranchAndBound.html',1,'idol::BranchAndBound&lt; NodeT &gt;'],['../classidol_1_1BranchAndBound.html#a96fec5e9e6f278c51ec788b317321616',1,'idol::BranchAndBound::BranchAndBound()=default'],['../classidol_1_1BranchAndBound.html#a15e010f0ecbb6ddde4ec3fee723564f0',1,'idol::BranchAndBound::BranchAndBound(const BranchAndBound &amp;t_rhs)'],['../classidol_1_1Optimizers_1_1BranchAndBound.html',1,'idol::Optimizers::BranchAndBound&lt; NodeInfoT &gt;']]],
  ['branchandbound_3c_20nodet_20_3e_17',['BranchAndBound&lt; NodeT &gt;',['../classidol_1_1Optimizers_1_1BranchAndBound.html',1,'idol::Optimizers']]],
  ['branchandboundcallback_18',['BranchAndBoundCallback',['../classidol_1_1BranchAndBoundCallback.html',1,'idol']]],
  ['branchandboundcallbackfactory_19',['BranchAndBoundCallbackFactory',['../classidol_1_1BranchAndBoundCallbackFactory.html',1,'idol']]],
  ['branchandboundcallbackfactory_3c_20idol_3a_3adefaultnodeinfo_20_3e_20',['BranchAndBoundCallbackFactory&lt; idol::DefaultNodeInfo &gt;',['../classidol_1_1BranchAndBoundCallbackFactory.html',1,'idol']]],
  ['branchandboundcallbacki_21',['BranchAndBoundCallbackI',['../classidol_1_1BranchAndBoundCallbackI.html',1,'idol']]],
  ['branchandcut_22',['branchandcut',['../classidol_1_1Optimizers_1_1Bilevel_1_1BranchAndCut.html',1,'idol::Optimizers::Bilevel::BranchAndCut'],['../classidol_1_1Bilevel_1_1BranchAndCut.html',1,'idol::Bilevel::BranchAndCut']]],
  ['branchingrule_23',['BranchingRule',['../classidol_1_1BranchingRule.html',1,'idol']]],
  ['branchingrulefactory_24',['BranchingRuleFactory',['../classidol_1_1BranchingRuleFactory.html',1,'idol']]],
  ['branchingrulefactory_3c_20idol_3a_3adefaultnodeinfo_20_3e_25',['BranchingRuleFactory&lt; idol::DefaultNodeInfo &gt;',['../classidol_1_1BranchingRuleFactory.html',1,'idol']]],
  ['branchingrulefactory_3c_20nodeinfot_20_3e_26',['BranchingRuleFactory&lt; NodeInfoT &gt;',['../classidol_1_1BranchingRuleFactory.html',1,'idol']]],
  ['branchingwithpriority_27',['branchingwithpriority',['../classidol_1_1BranchingRules_1_1BranchingWithPriority.html',1,'idol::BranchingRules::BranchingWithPriority&lt; NodeInfoT &gt;'],['../classidol_1_1BranchingWithPriority.html',1,'idol::BranchingWithPriority&lt; NodeT &gt;']]],
  ['breadthfirst_28',['breadthfirst',['../classidol_1_1NodeSelectionRules_1_1BreadthFirst.html',1,'idol::NodeSelectionRules::BreadthFirst&lt; NodeT &gt;'],['../classidol_1_1BreadthFirst.html',1,'idol::BreadthFirst']]],
  ['building_20and_20solving_20simple_20models_29',['Building and solving simple models',['../examples_mixed_integer.html#examples_mixed_integer_modeling',1,'']]]
];
