var searchData=
[
  ['idol_0',['idol',['../example_mixed_integer_bin_bap.html#autotoc_md2',1,'Implementation in idol'],['../example_mixed_integer_gap_bap.html#autotoc_md6',1,'Implementation in idol'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md14',1,'Implementation in idol']]],
  ['idol_20c_20library_1',['The &lt;span class=&quot;tt&quot;&gt;idol&lt;/span&gt; C++ Library',['../index.html#getting_started_with_idol',1,'']]],
  ['idol_20using_20cmake_2',['Linking with &lt;span class=&quot;tt&quot;&gt;idol&lt;/span&gt; using CMake',['../lib_installation.html#lib_linking',1,'']]],
  ['idol_5fcl_3',['What is idol_cl?',['../cli_basics.html#cli_what_is',1,'']]],
  ['implementation_20in_20idol_4',['Implementation in idol',['../example_mixed_integer_bin_bap.html#autotoc_md2',1,'Implementation in idol'],['../example_mixed_integer_gap_bap.html#autotoc_md6',1,'Implementation in idol'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md14',1,'Implementation in idol']]],
  ['in_20idol_5',['in idol',['../example_mixed_integer_bin_bap.html#autotoc_md2',1,'Implementation in idol'],['../example_mixed_integer_gap_bap.html#autotoc_md6',1,'Implementation in idol'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md14',1,'Implementation in idol']]],
  ['inequalities_6',['Deactivating Kleinart et al. (2020) Valid Inequalities',['../cli_bilevel_kkt.html#kkt_kleinert_vi',1,'']]],
  ['input_20format_7',['Input Format',['../cli_input_format.html',1,'']]],
  ['input_20format_20for_20bilevel_20problems_8',['Input Format for Bilevel Problems',['../cli_input_format_bilevel.html',1,'']]],
  ['input_20format_20for_20milps_9',['Input Format for MILPs',['../cli_input_format_milp.html',1,'']]],
  ['input_20format_20for_20robust_20problems_10',['Input Format for Robust Problems',['../cli_input_format_robust.html',1,'']]],
  ['install_11',['Step 4 — Install',['../build_from_source.html#step_install',1,'']]],
  ['installation_12',['Installation',['../cli_installation.html',1,'Installation'],['../lib_installation.html',1,'Installation'],['../lib_installation.html#lib_install',1,'Installation']]],
  ['installation_13',['Step 5 — Verify installation',['../build_from_source.html#step_verify',1,'']]],
  ['installation_20directory_14',['Custom installation directory',['../build_from_source.html#cmake_install_prefix',1,'']]],
  ['installation_20guidelines_15',['Installation guidelines',['../installation.html',1,'']]],
  ['instances_16',['Instances',['../cli_instances.html',1,'']]],
  ['instructions_17',['Build instructions',['../build_from_source.html#build_steps',1,'']]],
  ['integer_20bilevel_20optimization_18',['Mixed-integer bilevel optimization',['../examples_bilevel.html#examples_bilevel_mixed_integer',1,'']]],
  ['integer_20optimization_19',['integer optimization',['../examples_mixed_integer.html',1,'Mixed-integer optimization'],['../stable_features_mixed_integer.html',1,'Mixed-integer optimization']]],
  ['integrality_20constraints_20',['Integrality Constraints',['../example_mixed_integer_tsp_gurobi.html#autotoc_md12',1,'']]],
  ['interface_21',['Modeling interface',['../test_modeling_interface.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20cplex_22',['Interfacing Cplex',['../test_wrapper_Cplex.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20cplex_20via_20osi_23',['Interfacing Cplex via Osi',['../test_wrapper_OsiCplex.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20glpk_24',['Interfacing GLPK',['../test_wrapper_GLPK.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20gurobi_25',['Interfacing Gurobi',['../test_wrapper_Gurobi.html',1,'stable_features_mixed_integer']]],
  ['interfacing_20highs_26',['Interfacing HiGHS',['../test_wrapper_HiGHS.html',1,'stable_features_mixed_integer']]],
  ['introduction_27',['Introduction',['../cli_bilevel_kkt.html#kkt_introduction',1,'']]],
  ['is_20idol_5fcl_28',['What is idol_cl?',['../cli_basics.html#cli_what_is',1,'']]],
  ['is_20this_20a_20mip_20solver_29',['Is this a MIP Solver?',['../index.html#is_this_a_mip_solver',1,'']]],
  ['its_20kkt_20based_20single_20level_20reformulation_30',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]]
];
