var searchData=
[
  ['a_20branch_20and_20bound_20algorithm_0',['Creating a Branch-and-Bound Algorithm',['../lib_milp_branch_and_bound.html',1,'']]],
  ['a_20branch_20and_20bound_20specific_20callback_1',['Writing a Branch-and-Bound-Specific Callback',['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_specific',1,'']]],
  ['a_20build_20directory_2',['Step 2 — Create a build directory',['../build_from_source.html#step_build_dir',1,'']]],
  ['a_20first_20example_3',['A First Example',['../cli_bilevel_basics.html#cli_bilevel_basics_input_example',1,'A First Example'],['../cli_robust_basics.html#cli_robust_basics_input_example',1,'A First Example'],['../cli_robust_basics.html#cli_robust_basics_aro_input_example',1,'A First Example']]],
  ['a_20mip_20solver_4',['Is this a MIP Solver?',['../index.html#is_this_a_mip_solver',1,'']]],
  ['a_20model_20and_20what_20can_20you_20do_20with_20it_5',['What is a Model and What Can You Do with It?',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_what',1,'']]],
  ['a_20pessimistic_20bilevel_20problem_6',['Solving A Pessimistic Bilevel Problem',['../cli_bilevel_basics.html#cli_bilevel_basics_pessimistic',1,'']]],
  ['a_20toy_20example_7',['A Toy Example',['../lib_milp_basics.html#lib_milp_basics_hello_world',1,'']]],
  ['a_20two_20stage_20robust_20problem_8',['Solving a Two-Stage Robust Problem',['../cli_robust_basics.html#cli_robust_basics_aro_solving',1,'']]],
  ['a_20universal_20callback_9',['Writing a Universal Callback',['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_universal',1,'']]],
  ['about_10',['About',['../about.html',1,'']]],
  ['about_20branch_20and_20cut_20and_20price_11',['About Branch-and-Cut-and-Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'']]],
  ['about_20dantzig_20wolfe_20decomposition_12',['About Dantzig-Wolfe Decomposition',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_cg',1,'']]],
  ['accessing_20variables_13',['Accessing Variables',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_access',1,'']]],
  ['adding_20your_20own_20lazy_20cuts_14',['Adding Your Own Lazy Cuts',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_lazy_cuts',1,'']]],
  ['adding_20your_20own_20user_20cuts_15',['Adding Your Own User Cuts',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_user_cuts',1,'']]],
  ['advanced_20features_16',['More advanced features',['../examples_mixed_integer.html#examples_mixed_integer_mored_advanced_features',1,'']]],
  ['advanced_20topics_17',['Advanced Topics',['../lib_milp_basics.html#lib_milp_basics_advanced',1,'More Advanced Topics'],['../lib_milp_branch_and_bound.html#lib_milp_bnb_sub_pages',1,'More Advanced Topics'],['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced',1,'More Advanced Topics']]],
  ['ahead_18',['Strong Branching with Look Ahead',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_look_ahead',1,'']]],
  ['al_202020_20valid_20inequalities_19',['Deactivating Kleinart et al. (2020) Valid Inequalities',['../cli_bilevel_kkt.html#kkt_kleinert_vi',1,'']]],
  ['algorithm_20',['Creating a Branch-and-Bound Algorithm',['../lib_milp_branch_and_bound.html',1,'']]],
  ['algorithm_21',['algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'Branch-and-bound algorithm'],['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'Branch-and-price algorithm']]],
  ['amd64_22',['amd64',['../cli_installation.html#linux',1,'Linux (amd64)'],['../lib_installation.html#lib_install_linux',1,'Linux (amd64)']]],
  ['an_20exponential_20size_20model_23',['An Exponential-Size Model',['../example_mixed_integer_tsp_gurobi.html#autotoc_md7',1,'']]],
  ['an_20external_20solver_24',['Using an External Solver',['../lib_milp_basics.html#lib_milp_basics_solving',1,'']]],
  ['an_20optimistic_20bilevel_20problem_25',['Solving An Optimistic Bilevel Problem',['../cli_bilevel_basics.html#cli_bilevel_basics_optimistic',1,'']]],
  ['an_20optimization_20environment_26',['What is an Optimization Environment',['../lib_milp_basics_advanced_environment.html#lib_milp_basics_advanced_environment_what',1,'']]],
  ['and_20bound_20algorithm_27',['Creating a Branch-and-Bound Algorithm',['../lib_milp_branch_and_bound.html',1,'']]],
  ['and_20bound_20algorithm_28',['Branch-and-bound algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'']]],
  ['and_20bound_20specific_20callback_29',['Writing a Branch-and-Bound-Specific Callback',['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_specific',1,'']]],
  ['and_20build_30',['Step 3 — Configure and build',['../build_from_source.html#step_configure',1,'']]],
  ['and_20cut_20and_20price_31',['and Cut and Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'About Branch-and-Cut-and-Price'],['../lib_milp_branch_and_price.html',1,'Branch-and-Cut-and-Price']]],
  ['and_20moving_20models_32',['Copying and Moving Models',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_copy',1,'']]],
  ['and_20mps_33',['Example (.lp and .mps)',['../cli_milp_basics.html#cli_milp_example_lp',1,'']]],
  ['and_20optimizer_20factories_34',['Optimizers and Optimizer Factories',['../lib_milp_basics_advanced_optimizers.html',1,'lib_milp_basics']]],
  ['and_20parameters_35',['Handling of Default Tolerances and Parameters',['../lib_milp_basics_advanced_environment.html#lib_milp_basics_advanced_environment_tolerances',1,'']]],
  ['and_20price_36',['and Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'About Branch-and-Cut-and-Price'],['../lib_milp_branch_and_price.html',1,'Branch-and-Cut-and-Price']]],
  ['and_20price_20algorithm_37',['Branch-and-price algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'']]],
  ['and_20solving_20simple_20models_38',['Building and solving simple models',['../examples_mixed_integer.html#examples_mixed_integer_modeling',1,'']]],
  ['and_20what_20can_20you_20do_20with_20it_39',['What is a Model and What Can You Do with It?',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_what',1,'']]],
  ['any_20other_20solver_40',['Cannot find Cplex, GLPK, Gurobi, HiGHS, or any other solver',['../cannot_find_solver.html',1,'']]],
  ['arm64_41',['arm64',['../cli_installation.html#mac',1,'MacOs (arm64)'],['../lib_installation.html#lib_install_mac',1,'MacOs (arm64)']]],
  ['at_20once_42',['Creating Multiple Variables at Once',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_create_array',1,'']]],
  ['author_43',['Author',['../about.html#autotoc_md18',1,'']]],
  ['automatic_20download_20using_20cmake_20fetchcontent_44',['Automatic Download using CMake &lt;span class=&quot;tt&quot;&gt;FetchContent&lt;/span&gt;',['../lib_installation.html#lib_install_cmake',1,'']]],
  ['aux_20file_45',['Format of the &lt;span class=&quot;tt&quot;&gt;.aux&lt;/span&gt; File',['../cli_bilevel_basics.html#cli_bilevel_aux',1,'']]]
];
