var searchData=
[
  ['bab_0',['flp-bab',['../example_mixed_integer_flp_bab.html',1,'examples_mixed_integer']]],
  ['bap_1',['bap',['../example_mixed_integer_bin_bap.html',1,'bin-bap'],['../example_mixed_integer_gap_bap.html',1,'gap-bap']]],
  ['bard_20mibs_2',['moore-bard-mibs',['../example_bilevel_moore_bard_mibs.html',1,'examples_bilevel']]],
  ['based_20single_20level_20reformulation_3',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['basics_4',['Basics',['../lib_milp_basics.html',1,'Basics'],['../lib_milp_branch_and_bound.html#lib_milp_bnb_basics',1,'Basics']]],
  ['basics_20of_20the_20command_20line_20interface_20for_20bilevel_20optimization_5',['Basics of the Command Line Interface for Bilevel Optimization',['../cli_bilevel_basics.html',1,'']]],
  ['basics_20of_20the_20command_20line_20interface_20for_20milps_6',['Basics of the Command Line Interface for MILPs',['../cli_milp_basics.html',1,'']]],
  ['basics_20of_20the_20command_20line_20interface_20for_20robust_20problems_7',['Basics of the Command Line Interface for Robust Problems',['../cli_robust_basics.html',1,'']]],
  ['best_20bound_8',['Best Bound',['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_BestBound',1,'']]],
  ['best_20estimate_9',['Best Estimate',['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_BestEstimate',1,'']]],
  ['big_20m_20reformulation_10',['Using the Big-M Reformulation',['../cli_bilevel_kkt.html#kkt_big_m',1,'']]],
  ['bilevel_20optimization_11',['Bilevel Optimization',['../cli_bilevel_basics.html',1,'Basics of the Command Line Interface for Bilevel Optimization'],['../cli_tutorials.html#cli_tutorials_bilevel',1,'Bilevel Optimization']]],
  ['bilevel_20optimization_12',['Bilevel optimization',['../examples_bilevel.html',1,'Bilevel optimization'],['../stable_features_bilevel.html',1,'Bilevel optimization']]],
  ['bilevel_20optimization_13',['bilevel optimization',['../examples_bilevel.html#examples_bilevel_continuous',1,'Continuous bilevel optimization'],['../examples_bilevel.html#examples_bilevel_mixed_integer',1,'Mixed-integer bilevel optimization'],['../examples_bilevel.html#examples_bilevel_mixed_integer_pessimistic',1,'Pessimistic bilevel optimization']]],
  ['bilevel_20problem_14',['Bilevel Problem',['../cli_bilevel_basics.html#cli_bilevel_basics_pessimistic',1,'Solving A Pessimistic Bilevel Problem'],['../cli_bilevel_basics.html#cli_bilevel_basics_optimistic',1,'Solving An Optimistic Bilevel Problem']]],
  ['bilevel_20problems_20via_20its_20kkt_20based_20single_20level_20reformulation_15',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['bin_20bap_16',['bin-bap',['../example_mixed_integer_bin_bap.html',1,'examples_mixed_integer']]],
  ['bound_17',['Bound',['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_BestBound',1,'Best Bound'],['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_WorstBound',1,'Worst Bound']]],
  ['bound_20algorithm_18',['Creating a Branch-and-Bound Algorithm',['../lib_milp_branch_and_bound.html',1,'']]],
  ['bound_20algorithm_19',['Branch-and-bound algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'']]],
  ['bound_20rounding_20',['Bound Rounding',['../lib_milp_bnb_presolve.html#lib_milp_bnb_presolve_BoundRounding',1,'']]],
  ['bound_20specific_20callback_21',['Writing a Branch-and-Bound-Specific Callback',['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_specific',1,'']]],
  ['bound_20strengthening_22',['One Row Bound Strengthening',['../lib_milp_bnb_presolve.html#lib_milp_bnb_presolve_OneRowBoundStrengthening',1,'']]],
  ['bounds_23',['Reference for Dual Variable Bounds',['../cli_bilevel_kkt.html#kkt_big_m_def',1,'']]],
  ['bounds_20on_20the_20dual_20variables_24',['The File Format for Providing Bounds on the Dual Variables',['../cli_bilevel_kkt.html#kkt_big_m_file',1,'']]],
  ['branch_20and_20bound_20algorithm_25',['Creating a Branch-and-Bound Algorithm',['../lib_milp_branch_and_bound.html',1,'']]],
  ['branch_20and_20bound_20algorithm_26',['Branch-and-bound algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_bound',1,'']]],
  ['branch_20and_20bound_20specific_20callback_27',['Writing a Branch-and-Bound-Specific Callback',['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_specific',1,'']]],
  ['branch_20and_20cut_20and_20price_28',['Branch and Cut and Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'About Branch-and-Cut-and-Price'],['../lib_milp_branch_and_price.html',1,'Branch-and-Cut-and-Price']]],
  ['branch_20and_20price_20algorithm_29',['Branch-and-price algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'']]],
  ['branching_30',['Branching',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_bnb',1,'Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_full',1,'Full Strong Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_PseudoCost',1,'Pseudo Cost Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_restricted',1,'Restricted Strong Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching',1,'Strong Branching'],['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_UniformlyRandom',1,'Uniformly Random Branching']]],
  ['branching_20rule_31',['Writing Your Own Branching Rule',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_writing',1,'']]],
  ['branching_20rules_32',['Branching Rules',['../lib_milp_bnb_branching_rule.html',1,'lib_milp_branch_and_bound']]],
  ['branching_20with_20look_20ahead_33',['Strong Branching with Look Ahead',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_look_ahead',1,'']]],
  ['branching_20with_20phases_34',['Strong Branching with Phases',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_phases',1,'']]],
  ['branching_20with_20priorities_35',['Branching with Priorities',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_BranchingWithPriority',1,'']]],
  ['breadth_20first_36',['Breadth First',['../lib_milp_bnb_node_selection.html#lib_milp_bnb_node_selection_BreadthFirst',1,'']]],
  ['build_37',['Step 3 — Configure and build',['../build_from_source.html#step_configure',1,'']]],
  ['build_20directory_38',['Step 2 — Create a build directory',['../build_from_source.html#step_build_dir',1,'']]],
  ['build_20examples_39',['Build examples',['../build_from_source.html#cmake_examples',1,'']]],
  ['build_20from_20source_40',['Build from source',['../build_from_source.html',1,'']]],
  ['build_20instructions_41',['Build instructions',['../build_from_source.html#build_steps',1,'']]],
  ['build_20tests_42',['Build tests',['../build_from_source.html#cmake_tests',1,'']]],
  ['building_20and_20solving_20simple_20models_43',['Building and solving simple models',['../examples_mixed_integer.html#examples_mixed_integer_modeling',1,'']]]
];
