var searchData=
[
  ['parallel_20pricing_0',['Parallel Pricing',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_parallel',1,'']]],
  ['parameters_1',['Handling of Default Tolerances and Parameters',['../lib_milp_basics_advanced_environment.html#lib_milp_basics_advanced_environment_tolerances',1,'']]],
  ['party_20tools_2',['Third Party Tools',['../about.html#autotoc_md22',1,'']]],
  ['path_20problem_20rspp_3',['Resource-constrained shortest path problem (RSPP)',['../example_mixed_integer_rspp_bap.html#autotoc_md7',1,'']]],
  ['pess_4',['zeng-pess',['../example_bilevel_zeng_pess.html',1,'examples_bilevel']]],
  ['pessimistic_20bilevel_20optimization_5',['Pessimistic bilevel optimization',['../examples_bilevel.html#examples_bilevel_mixed_integer_pessimistic',1,'']]],
  ['pessimistic_20bilevel_20problem_6',['Solving A Pessimistic Bilevel Problem',['../cli_bilevel_basics.html#cli_bilevel_basics_pessimistic',1,'']]],
  ['phase_20i_7',['Making the Master Problem Feasible (Phase I)',['../lib_milp_branch_and_price_cg_phaseI.html',1,'lib_milp_branch_and_price']]],
  ['phases_8',['Strong Branching with Phases',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_StrongBranching_phases',1,'']]],
  ['planes_9',['Cutting Planes',['../lib_milp_bnb_cutting_planes.html',1,'lib_milp_branch_and_bound']]],
  ['pool_10',['The Cut Pool',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_cut_pool',1,'']]],
  ['pool_20clean_20up_11',['Column Pool Clean Up',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_clean_up',1,'']]],
  ['pool_20size_12',['Solution Pool Size',['../lib_milp_bnb_options.html#lib_milp_bnb_options_solution_pool',1,'']]],
  ['presolve_13',['Presolve',['../lib_milp_bnb_presolve.html',1,'lib_milp_branch_and_bound']]],
  ['price_14',['Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'About Branch-and-Cut-and-Price'],['../lib_milp_branch_and_price.html',1,'Branch-and-Cut-and-Price']]],
  ['price_20algorithm_15',['Branch-and-Price algorithm',['../example_mixed_integer_rspp_bap.html#autotoc_md8',1,'']]],
  ['price_20algorithm_16',['Branch-and-price algorithm',['../examples_mixed_integer.html#examples_mixed_integer_branch_and_price',1,'']]],
  ['pricing_17',['Pricing',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_parallel',1,'Parallel Pricing'],['../lib_milp_branch_and_price_cg_HeuristicPricing.html',1,'Using Heuristics for Pricing']]],
  ['pricing_20callback_18',['Using Your Own Pricing Callback',['../lib_milp_branch_and_price_cg_callback.html',1,'lib_milp_branch_and_price']]],
  ['pricing_20problem_19',['Deriving the Pricing Problem',['../example_mixed_integer_gap_bap.html#autotoc_md5',1,'']]],
  ['pricing_20subproblem_20',['Pricing Subproblem',['../example_mixed_integer_rspp_bap.html#autotoc_md10',1,'']]],
  ['priorities_21',['Branching with Priorities',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_BranchingWithPriority',1,'']]],
  ['problem_22',['Problem',['../example_mixed_integer_gap_bap.html#autotoc_md5',1,'Deriving the Pricing Problem'],['../cli_bilevel_basics.html#cli_bilevel_basics_pessimistic',1,'Solving A Pessimistic Bilevel Problem'],['../cli_robust_basics.html#cli_robust_basics_aro_solving',1,'Solving a Two-Stage Robust Problem'],['../cli_bilevel_basics.html#cli_bilevel_basics_optimistic',1,'Solving An Optimistic Bilevel Problem'],['../example_mixed_integer_rspp_bap.html#autotoc_md9',1,'The Master Problem']]],
  ['problem_20feasible_20phase_20i_23',['Making the Master Problem Feasible (Phase I)',['../lib_milp_branch_and_price_cg_phaseI.html',1,'lib_milp_branch_and_price']]],
  ['problem_20rspp_24',['Resource-constrained shortest path problem (RSPP)',['../example_mixed_integer_rspp_bap.html#autotoc_md7',1,'']]],
  ['problems_25',['Basics of the Command Line Interface for Robust Problems',['../cli_robust_basics.html',1,'']]],
  ['problems_20via_20its_20kkt_20based_20single_20level_20reformulation_26',['Solving Bilevel Problems via its KKT-Based Single-Level Reformulation',['../cli_bilevel_kkt.html',1,'']]],
  ['providing_20bounds_20on_20the_20dual_20variables_27',['The File Format for Providing Bounds on the Dual Variables',['../cli_bilevel_kkt.html#kkt_big_m_file',1,'']]],
  ['pseudo_20cost_20branching_28',['Pseudo Cost Branching',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_PseudoCost',1,'']]]
];
