var searchData=
[
  ['c_20library_0',['C Library',['../index.html#getting_started_with_idol',1,'The &lt;span class=&quot;tt&quot;&gt;idol&lt;/span&gt; C++ Library'],['../lib_tutorials.html',1,'Tutorials for the C++ Library']]],
  ['callback_1',['Callback',['../lib_milp_branch_and_price_cg_callback.html',1,'Using Your Own Pricing Callback'],['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_specific',1,'Writing a Branch-and-Bound-Specific Callback'],['../lib_milp_bnb_callbacks.html#lib_milp_bnb_callbacks_universal',1,'Writing a Universal Callback']]],
  ['callbacks_2',['Callbacks',['../lib_milp_bnb_callbacks.html',1,'lib_milp_branch_and_bound']]],
  ['can_20you_20do_20with_20it_3',['What is a Model and What Can You Do with It?',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_what',1,'']]],
  ['cannot_20find_20cplex_20glpk_20gurobi_20highs_20or_20any_20other_20solver_4',['Cannot find Cplex, GLPK, Gurobi, HiGHS, or any other solver',['../cannot_find_solver.html',1,'']]],
  ['ccg_5',['flp-ccg',['../example_robust_flp_ccg.html',1,'examples_robust']]],
  ['cgl_6',['Using the Coin-OR Cut Generation Library (Cgl)',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_cgl',1,'']]],
  ['cgl_20support_7',['Enable Cgl support',['../build_from_source.html#cmake_cgl',1,'']]],
  ['changing_20the_20scoring_20function_8',['Changing the Scoring Function',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_scoring',1,'']]],
  ['changing_20the_20underlying_20milp_20solver_9',['Changing the Underlying MILP Solver',['../cli_bilevel_kkt.html#kkt_other_milp_solver',1,'']]],
  ['cite_10',['How to cite',['../about.html#autotoc_md15',1,'']]],
  ['clean_20up_11',['Column Pool Clean Up',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_clean_up',1,'']]],
  ['clone_20the_20repository_12',['Step 1 — Clone the repository',['../build_from_source.html#step_clone',1,'']]],
  ['cmake_13',['Linking with &lt;span class=&quot;tt&quot;&gt;idol&lt;/span&gt; using CMake',['../lib_installation.html#lib_linking',1,'']]],
  ['cmake_20fetchcontent_14',['Automatic Download using CMake &lt;span class=&quot;tt&quot;&gt;FetchContent&lt;/span&gt;',['../lib_installation.html#lib_install_cmake',1,'']]],
  ['cmake_20options_15',['CMake Options',['../build_from_source.html#cmake_options',1,'']]],
  ['coin_20or_20cut_20generation_20library_20cgl_16',['Using the Coin-OR Cut Generation Library (Cgl)',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_cgl',1,'']]],
  ['column_20generation_20via_20in_20out_20separation_17',['Stabilizing Column Generation via in-out Separation',['../lib_milp_branch_and_price_cg_in_out.html',1,'lib_milp_branch_and_price']]],
  ['column_20pool_20clean_20up_18',['Column Pool Clean Up',['../lib_milp_branch_and_price_cg_options.html#lib_milp_branch_and_price_cg_options_clean_up',1,'']]],
  ['command_20line_20interface_19',['Tutorials for the Command Line Interface',['../cli_tutorials.html',1,'']]],
  ['command_20line_20interface_20for_20bilevel_20optimization_20',['Basics of the Command Line Interface for Bilevel Optimization',['../cli_bilevel_basics.html',1,'']]],
  ['command_20line_20interface_20for_20milps_21',['Basics of the Command Line Interface for MILPs',['../cli_milp_basics.html',1,'']]],
  ['command_20line_20interface_20for_20robust_20problems_22',['Basics of the Command Line Interface for Robust Problems',['../cli_robust_basics.html',1,'']]],
  ['configure_20and_20build_23',['Step 3 — Configure and build',['../build_from_source.html#step_configure',1,'']]],
  ['constraint_20matrix_20uncertainty_24',['Constraint Matrix Uncertainty',['../cli_robust_basics.html#cli_robust_mat_file',1,'']]],
  ['constraints_25',['Constraints',['../lib_milp_basics_advanced_constraints.html',1,'Constraints'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md10',1,'Degree Constraints'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md12',1,'Integrality Constraints'],['../example_mixed_integer_tsp_gurobi.html#autotoc_md11',1,'Sub-Tour Elimination Constraints']]],
  ['constructor_26',['Using the Variable Constructor',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_create_env',1,'']]],
  ['continuous_20bilevel_20optimization_27',['Continuous bilevel optimization',['../examples_bilevel.html#examples_bilevel_continuous',1,'']]],
  ['copying_20and_20moving_20models_28',['Copying and Moving Models',['../lib_milp_basics_advanced_models.html#lib_milp_basics_advanced_models_copy',1,'']]],
  ['cost_20branching_29',['Pseudo Cost Branching',['../lib_milp_bnb_branching_rule.html#lib_milp_bnb_branching_rule_PseudoCost',1,'']]],
  ['cplex_30',['sudoku-cplex',['../example_mixed_integer_sudoku_cplex.html',1,'examples_mixed_integer']]],
  ['cplex_20glpk_20gurobi_20highs_20or_20any_20other_20solver_31',['Cannot find Cplex, GLPK, Gurobi, HiGHS, or any other solver',['../cannot_find_solver.html',1,'']]],
  ['create_20a_20build_20directory_32',['Step 2 — Create a build directory',['../build_from_source.html#step_build_dir',1,'']]],
  ['creating_20a_20branch_20and_20bound_20algorithm_33',['Creating a Branch-and-Bound Algorithm',['../lib_milp_branch_and_bound.html',1,'']]],
  ['creating_20multiple_20variables_20at_20once_34',['Creating Multiple Variables at Once',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_create_array',1,'']]],
  ['creating_20variables_35',['Creating Variables',['../lib_milp_basics_advanced_variables.html#lib_milp_basics_advanced_variables_create',1,'']]],
  ['creating_20your_20own_20optimizer_36',['Creating Your Own Optimizer',['../lib_milp_basics_advanced_create_optimizer.html',1,'lib_milp_basics']]],
  ['custom_20installation_20directory_37',['Custom installation directory',['../build_from_source.html#cmake_install_prefix',1,'']]],
  ['cut_20and_20price_38',['Cut and Price',['../lib_milp_branch_and_price.html#lib_milp_branch_and_price_advanced_bap',1,'About Branch-and-Cut-and-Price'],['../lib_milp_branch_and_price.html',1,'Branch-and-Cut-and-Price']]],
  ['cut_20generation_20library_20cgl_39',['Using the Coin-OR Cut Generation Library (Cgl)',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_cgl',1,'']]],
  ['cut_20pool_40',['The Cut Pool',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_cut_pool',1,'']]],
  ['cuts_41',['Cuts',['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_lazy_cuts',1,'Adding Your Own Lazy Cuts'],['../lib_milp_bnb_cutting_planes.html#lib_milp_bnb_cutting_planes_user_cuts',1,'Adding Your Own User Cuts']]],
  ['cutting_20planes_42',['Cutting Planes',['../lib_milp_bnb_cutting_planes.html',1,'lib_milp_branch_and_bound']]]
];
