//
// Created by henri on 09.01.26.
//

#ifndef IDOL_CRITICALVALUECOLUMNANDCONSTRAINTGENERATION_H
#define IDOL_CRITICALVALUECOLUMNANDCONSTRAINTGENERATION_H

#endif //IDOL_CRITICALVALUECOLUMNANDCONSTRAINTGENERATION_H