import xml.etree.ElementTree as ET
import json

def parse_section(section):
    result = {}
    result["name"] = section.get("name")
    overall_results = section.find("OverallResults")
    if overall_results is not None:
        result["successes"] = int(overall_results.get("successes"))
        result["failures"] = int(overall_results.get("failures"))
        result["skipped"] = overall_results.get("skipped") == "true"
        n = max(result["successes"] + result["failures"], 1)
        result["progress"] = None if result["skipped"] else result["successes"] / n * 100
    return result

def parse_test_case(test_case):
    result = {}
    result["name"] = test_case.get("name")
    result["description"] = test_case.get("description")
    result["sections"] = []
    result["exceptions"] = []
    for section in test_case.findall("Section"):
        result["sections"].append(parse_section(section))
    for exception in test_case.findall("Exception"):
        result["exceptions"].append("Exception thrown: " + exception.text)
    n = sum([not section["skipped"] for section in result["sections"]])
    if n == 0:
        result["progress"] = None
    else:
        result["progress"] = sum(section["progress"] or 0 for section in result["sections"]) / n
    return result

def parse_report(xml_path):
    """Parse the XML report and print the test case names."""
    # Parse the XML file

    result = {}

    tree = ET.parse(xml_path)
    root = tree.getroot()

    executable = root.get("name")
    result["executable"] = executable
    result["tags"] = {}

    for test_case in root.findall(".//TestCase"):
        tag = test_case.get("tags")
        if tag not in result["tags"]:
            result["tags"][tag] = {
                "test_cases": [],
            }
        result["tags"][tag]["test_cases"].append(parse_test_case(test_case))

    return result

def get_progress_color(progress):

    if progress is None: return "progress-NA"

    progress = max(0, min(100, progress))  # Ensure it's between 0 and 100

    if progress <= 25: return "progress-0"
    if progress <= 50: return "progress-25"
    if progress <= 75: return "progress-50"
    if progress < 100: return "progress-75"
    return "progress-100"

def generate_md(xml_path, db):

    base_name = xml_path.split("/")[-1]
    without_extension = base_name.split(".")[0]
    name = db[without_extension]["name"] if without_extension in db else without_extension
    brief = db[without_extension]["brief"] if without_extension in db else "..."

    result = "\\page " + without_extension + " " + name + "\n"
    result += "\\brief " + brief + "\n\n"

    result += "[TOC]\n\n"

    try:
        report = parse_report(xml_path)
        with open(xml_path, "r") as f: xml_report = f.read()
    except Exception as e:
        result += f"Error parsing report {xml_path}: {e}"
        return result

    result += "<div class=\"tabbed\">\n<ul>\n"
    result += "<li><b class=\"tab-title\">Formatted</b>"

    for tag_name, tag in report["tags"].items():

        tag_name = tag_name.replace("[", "").replace("]", "")

        #result += "\\subsection " + without_extension + "_" + tag_name + " " + tag_name + "\n"
        result += "<h2>" + tag_name + "</h2>\n"

        for test_case in tag["test_cases"]:
            result += "<h3>" + test_case["name"] + "</h3>\n"
            result += "<div class=\"full_width_table\">\n<table>\n"
            result += "<tr><th class=\"test-report-table-section\">Tested Feature</th><th>Outcome</th></tr>\n"

            for section in test_case["sections"]:
                section_name = section["name"]
                section_progress = section["progress"]
                section_progress_str = f"{section_progress:.0f} %" if section_progress is not None else "-"
                section_progress_color = get_progress_color(section_progress)
                result += "<tr><td>" + section_name + "</td><td class=\""+ section_progress_color + "\">" + section_progress_str + "</td></tr>\n"
            for exception in test_case["exceptions"]:
                result += "<tr><td colspan=\"2\" class=\"test-report-table-exception\">" + exception + "</td></tr>\n"

            result += "</table>\n</div>\n"
        result += "</li>"

    result += "<li><b class=\"tab-title\">Raw</b>\n"
    result += "This is the raw XML report generated by Catch2.\n"
    result += (f"```xml\n"
               f"{xml_report}\n"
               f"```\n")
    result += "</li>\n"

    result += "</ul>\n</div>\n"

    return result

import sys

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python test_report.py <path_to_report>")
        sys.exit(1)

    # Load the database
    with open("_ext/test_reports.json", "r") as f:
        db = json.load(f)

    # Path to the XML report file
    xml_path = sys.argv[1]
    md = generate_md(xml_path, db)
    print(md)
