//
// Created by henri on 28/11/22.
//

#ifndef IDOL_ATTRIBUTES_MODEL_H
#define IDOL_ATTRIBUTES_MODEL_H

#include "Attributes.h"

// RHS
IDOL_CREATE_ATTRIBUTE_CLASS(Rhs)

IDOL_CREATE_ATTRIBUTE_TYPE(Rhs, Rhs, 1)
IDOL_CREATE_ATTRIBUTE(Rhs, Rhs, 0, Expr)


// OBJ
IDOL_CREATE_ATTRIBUTE_CLASS(Obj)

IDOL_CREATE_ATTRIBUTE_TYPE(Obj, Obj, 1)
IDOL_CREATE_ATTRIBUTE(Obj, Obj, 0, Expr)

IDOL_CREATE_ATTRIBUTE_TYPE(Obj, Constant, 1)
IDOL_CREATE_ATTRIBUTE(Obj, Constant, 0, Const)

IDOL_CREATE_ATTRIBUTE_TYPE(Obj, IDOL_int, 1)
IDOL_CREATE_ATTRIBUTE(Obj, IDOL_int, 0, Sense)

// MATRIX
IDOL_CREATE_ATTRIBUTE_CLASS(Matrix)

IDOL_CREATE_ATTRIBUTE_TYPE(Matrix, Constant, 1)
IDOL_CREATE_ATTRIBUTE(Matrix, Constant, 0, Coeff)

#endif //IDOL_ATTRIBUTES_MODEL_H
